{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/attendance",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-calendar-check",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Attendance Board"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"15737236-14D5-5B97-A9C4-68AAA977F65E"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"384DE11A-FE3F-5439-A2A1-585165791AFC"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"CC1E66F0-C470-5554-A1F6-1199F3B1B4C8"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"card-panel"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"div"
                        }
                    },
                    "items":[
                        {
                            "json":{
                                "location":{
                                    "x":1,
                                    "y":1
                                },
                                "styleClass":"card-title",
                                "text":"Filter"
                            },
                            "location":"1,1",
                            "typeName":"bootstrapcomponents-label",
                            "typeid":47,
                            "uuid":"E891A69D-AFF5-5154-90EF-9F7D9AF69798"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-3 mb-2"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"form-label",
                                                "text":"Day"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"4B653E65-9E46-5F63-A2AF-19D0C5E4C375"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"boardDate",
                                                "format":"EEE dd-MM-yyyy",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onDataChangeMethodID":"542DB65D-6F8F-5115-914A-A13E408E2DD4",
                                                "styleClass":"form-control"
                                            },
                                            "location":"2,2",
                                            "name":"fld_date",
                                            "typeName":"bootstrapcomponents-calendar",
                                            "typeid":47,
                                            "uuid":"9BCFA44A-77D4-5EF4-B9FC-182808F2F83C"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"8207EB18-D3EA-557F-B7A5-0A8E40387D36"
                                },
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-3 mb-2"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"form-label",
                                                "text":"Department"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"3DCC568F-1696-54EE-A13A-1843FE57D118"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"departmentFilter",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onDataChangeMethodID":"F16EB7F2-E57D-5313-A90B-7A0C218280BA",
                                                "placeholderText":"All",
                                                "valuelistID":"DF1712FB-9977-5A54-AF95-26B2697BC8E7"
                                            },
                                            "location":"2,2",
                                            "name":"fld_department",
                                            "typeName":"bootstrapcomponents-combobox",
                                            "typeid":47,
                                            "uuid":"8785C80E-BD35-5688-91CD-5F8914E4AE10"
                                        }
                                    ],
                                    "location":"2,2",
                                    "typeid":46,
                                    "uuid":"39B2A7A9-9D35-5EF0-8BCC-AE317670B945"
                                },
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-3 mb-2"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"form-label",
                                                "text":"Status"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"3CF65051-EB81-5D47-94A8-60FCBD5D8FA0"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"statusFilter",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onDataChangeMethodID":"F16EB7F2-E57D-5313-A90B-7A0C218280BA",
                                                "placeholderText":"All",
                                                "valuelistID":"70BB9F1C-35DB-59BB-8BCF-56DCF7E1A56E"
                                            },
                                            "location":"2,2",
                                            "name":"fld_status",
                                            "typeName":"bootstrapcomponents-combobox",
                                            "typeid":47,
                                            "uuid":"6786A5CE-EF51-5F94-8AE1-D22308948DAF"
                                        }
                                    ],
                                    "location":"3,3",
                                    "typeid":46,
                                    "uuid":"94C4BF0E-2E41-5B52-9108-B078E7847AD4"
                                },
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-3 mb-2 d-flex align-items-end"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-chevron-left",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "onActionMethodID":"73E6B590-8B26-524D-B9AE-354803382A3A",
                                                "styleClass":"btn btn-outline-secondary me-1",
                                                "text":"",
                                                "toolTipText":"Previous day"
                                            },
                                            "location":"1,1",
                                            "name":"btn_prev",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"F2AF1285-515D-5129-AB56-9287735E98A8"
                                        },
                                        {
                                            "json":{
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onActionMethodID":"C4C97D32-4CBD-5ED1-BC75-D04CAF8E7563",
                                                "styleClass":"btn btn-outline-secondary me-1",
                                                "text":"Today"
                                            },
                                            "location":"2,2",
                                            "name":"btn_today",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"377D1D07-C0ED-5D9B-9C1C-9518B63661FF"
                                        },
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-chevron-right",
                                                "location":{
                                                    "x":3,
                                                    "y":3
                                                },
                                                "onActionMethodID":"05F03932-5432-55B0-BB5C-8069EF21DF83",
                                                "styleClass":"btn btn-outline-secondary",
                                                "text":"",
                                                "toolTipText":"Next day"
                                            },
                                            "location":"3,3",
                                            "name":"btn_next",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"573E111A-AA6D-5EE9-90E2-109732DF79AD"
                                        }
                                    ],
                                    "location":"4,4",
                                    "typeid":46,
                                    "uuid":"58DAA61E-234B-5954-82BF-8361CD85C3B6"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"3A737F38-A2EB-5310-8439-CE0D8DF11DBE"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-12 filter-actions"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-rotate",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "onActionMethodID":"C698D439-8994-5BF7-A0CA-F43B2EA23BC7",
                                                "styleClass":"btn btn-primary me-2",
                                                "text":"Recalculate"
                                            },
                                            "location":"1,1",
                                            "name":"btn_recalc",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"2F4D54B3-4820-5011-821C-5F8CA78A2DF4"
                                        },
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-eraser",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onActionMethodID":"D2F05F89-65E5-58FE-9211-AF6174287301",
                                                "styleClass":"btn btn-outline-secondary",
                                                "text":"Clear filters"
                                            },
                                            "location":"2,2",
                                            "name":"btn_clear",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"90CCE412-3902-51CA-8B8F-D3B8244C5849"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"F7CE2B74-5F73-5E10-898F-2F28A5C55BDA"
                                }
                            ],
                            "location":"3,3",
                            "typeid":46,
                            "uuid":"84143D87-7066-5C89-9C73-0FEC8D8E2AC6"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"9EDE5F30-E6F6-5B91-870E-14AB161FFC72"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"card-panel"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"div"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"grid-toolbar"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"div"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "dataProviderID":"summaryText",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"summary-text"
                                    },
                                    "location":"1,1",
                                    "name":"lbl_summary",
                                    "typeName":"bootstrapcomponents-datalabel",
                                    "typeid":47,
                                    "uuid":"3B84905B-3815-5B06-BD1E-59FA7F1FB04F"
                                },
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-file-excel",
                                        "location":{
                                            "x":2,
                                            "y":2
                                        },
                                        "onActionMethodID":"0BEA2F1D-D524-56A7-8931-FE669F15753C",
                                        "styleClass":"btn btn-sm btn-outline-secondary",
                                        "text":"Export",
                                        "toolTipText":"Download as CSV (opens in Excel)"
                                    },
                                    "location":"2,2",
                                    "name":"btn_export",
                                    "typeName":"bootstrapcomponents-button",
                                    "typeid":47,
                                    "uuid":"3AAB2E90-22A8-5667-804B-EAEB20FB2B12"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"E0FA9A78-0896-5976-9349-09DA03C86C37"
                        },
                        {
                            "json":{
                                "columns":[
                                    {
                                        "dataprovider":"employee_id",
                                        "filterType":"VALUELIST",
                                        "headerTitle":"Employee",
                                        "minWidth":110,
                                        "svyUUID":"7DE21BD9-CB64-5A45-820D-F57F9E42F13D",
                                        "valuelist":"1878CB17-9579-5E12-9933-F3B964B5551E"
                                    },
                                    {
                                        "dataprovider":"attendance_to_employees.department_id",
                                        "filterType":"VALUELIST",
                                        "headerTitle":"Department",
                                        "minWidth":110,
                                        "svyUUID":"7DD51B0A-43EE-5938-BACC-465398D9D8CF",
                                        "valuelist":"DF1712FB-9977-5A54-AF95-26B2697BC8E7"
                                    },
                                    {
                                        "dataprovider":"shift_id",
                                        "filterType":"VALUELIST",
                                        "headerTitle":"Shift",
                                        "minWidth":110,
                                        "svyUUID":"9650C05B-5171-5FDA-85FD-B1629A31766F",
                                        "valuelist":"EB21EBB8-FA70-546E-8D0D-6621F7B072B5"
                                    },
                                    {
                                        "dataprovider":"check_in",
                                        "filterType":"TEXT",
                                        "format":"HH:mm",
                                        "headerTitle":"In",
                                        "minWidth":110,
                                        "svyUUID":"2A275DA6-6B4F-50FD-9461-BE997C3FDF16"
                                    },
                                    {
                                        "dataprovider":"check_out",
                                        "filterType":"TEXT",
                                        "format":"HH:mm",
                                        "headerTitle":"Out",
                                        "minWidth":110,
                                        "svyUUID":"002CFA8F-8707-55D8-A354-ABFAE03AB7D9"
                                    },
                                    {
                                        "dataprovider":"worked_minutes",
                                        "filterType":"TEXT",
                                        "headerTitle":"Worked (min)",
                                        "minWidth":110,
                                        "svyUUID":"FD9F3DD9-8E6B-551B-83ED-8DEC0D0C7581"
                                    },
                                    {
                                        "dataprovider":"late_minutes",
                                        "filterType":"TEXT",
                                        "headerTitle":"Late (min)",
                                        "minWidth":110,
                                        "svyUUID":"B6CF2B96-0321-5647-925B-56A68980CD93"
                                    },
                                    {
                                        "dataprovider":"overtime_minutes",
                                        "filterType":"TEXT",
                                        "headerTitle":"OT (min)",
                                        "minWidth":110,
                                        "svyUUID":"16BCF607-38F8-5987-B95F-9AE6DC757A4E"
                                    },
                                    {
                                        "dataprovider":"status",
                                        "filterType":"VALUELIST",
                                        "headerTitle":"Status",
                                        "minWidth":110,
                                        "showAs":"html",
                                        "svyUUID":"2BF8B7DB-9BEF-5A2C-912F-438D8E04DA00",
                                        "valuelist":"03506EDE-09FA-5173-A770-2F8744724922"
                                    },
                                    {
                                        "dataprovider":"remarks",
                                        "filterType":"TEXT",
                                        "headerTitle":"Remarks",
                                        "minWidth":110,
                                        "svyUUID":"021F4D85-F07D-5788-8BE9-4EC7609404A1"
                                    }
                                ],
                                "location":{
                                    "x":2,
                                    "y":2
                                },
                                "myFoundset":{
                                    "foundsetSelector":""
                                },
                                "readOnly":true,
                                "responsiveHeight":460,
                                "rowHeight":32
                            },
                            "location":"2,2",
                            "name":"grid",
                            "typeName":"aggrid-groupingtable",
                            "typeid":47,
                            "uuid":"4AE790B5-05E6-5BB1-97FB-029C008E2C03"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"grid-footer"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"div"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-hand-pointer",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "onActionMethodID":"646782DD-EB65-58D8-A94E-FC29F66B9548",
                                        "styleClass":"btn btn-sm btn-primary",
                                        "text":"Edit punches of selected employee"
                                    },
                                    "location":"1,1",
                                    "name":"btn_punches",
                                    "typeName":"bootstrapcomponents-button",
                                    "typeid":47,
                                    "uuid":"1EF87E52-93BE-5C83-99EE-CA240A163B92"
                                },
                                {
                                    "json":{
                                        "location":{
                                            "x":2,
                                            "y":2
                                        },
                                        "styleClass":"help-text",
                                        "text":"Days with no punches become Absent only after the day (or overnight shift) is over."
                                    },
                                    "location":"2,2",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"D912E9BC-2165-5FEA-A740-60E136576F2A"
                                }
                            ],
                            "location":"3,3",
                            "typeid":46,
                            "uuid":"A4EF4337-3D20-55DA-814C-32B5CA0E41BB"
                        }
                    ],
                    "location":"3,3",
                    "typeid":46,
                    "uuid":"E04C72D8-7C02-501E-9E4C-FEFA8DEC0400"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"67A5033A-D8B1-5441-AAB5-3D1D4ECBB45D"
        }
    ],
    "name":"attendance_board",
    "navigatorID":"-1",
    "onLoadMethodID":"214F46EF-B635-5A5D-9EC0-8DD85C2C9CC7",
    "onShowMethodID":"487BC55F-12FC-550A-AD38-AA10D6162DF8",
    "typeid":3,
    "uuid":"5B626573-BEB0-571E-B255-85A7971A5991"
}