{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-key",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Change Password"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"F95B5D3E-E952-535F-BCD7-CCCF853982B6"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"A3CF4011-7CCC-592C-A4D8-C6CDECC3FA8E"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"888F3350-F85F-515D-A3AF-B2D44A33929B"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-md-8 col-lg-5"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_current",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Current password"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"5E8AB049-AC00-58FC-BF85-602312148E80"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"currentPassword",
                                                                "inputType":"password",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_current",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"7758422E-CC36-5DC0-90CA-11AB33A65FDD"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"C73E5E06-3748-517E-8CBB-CF6A2E673D52"
                                                }
                                            ],
                                            "location":"1,1",
                                            "typeid":46,
                                            "uuid":"1B3ED51D-35B6-5CF9-AB26-3997B0132F60"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_new",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"New password"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"D67A5D43-6E59-5ACE-A78F-B7C5053E94E1"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"newPassword",
                                                                "inputType":"password",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"At least 8 characters, letters and numbers",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_new",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"438379D5-D5FB-52F7-8D24-D51DE5CA9025"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"A1CB85EF-970A-550B-BCEC-516BED805FEE"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"2BDF35E7-A4E0-56CC-A0A2-594990919069"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_confirm",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Confirm new password"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"8F661B9F-CE1E-59C1-868F-DD613C60EC78"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"confirmPassword",
                                                                "inputType":"password",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"671C77C2-AE2F-58BF-993D-0EF62D16DB7E",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_confirm",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"1748D864-8D8E-51AA-BE7C-98ADE0C7D78B"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"EBE49D24-6AF4-5A78-92C5-F84436E3D780"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"2A045A36-F1E9-5F6A-B166-9F9B79682FAE"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"message",
                                                "location":{
                                                    "x":4,
                                                    "y":4
                                                },
                                                "showAs":"text",
                                                "styleClass":"login-error"
                                            },
                                            "location":"4,4",
                                            "name":"lbl_message",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"DC05E05B-F715-5DFA-A55E-A7E89F44C024"
                                        },
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-save",
                                                "location":{
                                                    "x":5,
                                                    "y":5
                                                },
                                                "onActionMethodID":"671C77C2-AE2F-58BF-993D-0EF62D16DB7E",
                                                "styleClass":"btn btn-primary",
                                                "text":"Change password"
                                            },
                                            "location":"5,5",
                                            "name":"btn_save",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"447262B4-88B7-53C5-ACFB-84F2585571B9"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"0A03595B-99F2-51A8-A798-C344362EAD32"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"C4DB219C-0604-5E1E-9B1E-07600D67D44B"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"B1557589-02DC-505A-AE8E-1BD1F5CADB93"
                },
                {
                    "json":{
                        "dataProviderID":"scopes.settings.appName",
                        "location":{
                            "x":3,
                            "y":3
                        },
                        "styleClass":"d-none",
                        "styleClassExpression":"scopes.settings.themeClass"
                    },
                    "location":"3,3",
                    "name":"theme_marker",
                    "typeName":"bootstrapcomponents-datalabel",
                    "typeid":47,
                    "uuid":"C735D41E-326A-50D0-AC11-643F72E620A6"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"79D1550A-8618-5376-A66D-0216C89BFEBE"
        }
    ],
    "name":"change_password",
    "navigatorID":"-1",
    "onShowMethodID":"BC8D01D5-725C-5062-A2B5-C16FC0C156A8",
    "typeid":3,
    "uuid":"53E53DB4-2137-530A-8F0E-51831514EC10"
}