{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-gauge",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Dashboard"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"C8CD636D-EBC7-5970-90AA-6BCCBCE449A3"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"A1167A2E-E377-5631-9D44-DB21FEA41A82"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"5A26AD65-ADB8-5B89-B50E-91B4B78D303D"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mb-2"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "dataProviderID":"greeting",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "showAs":"text",
                                        "styleClass":"text-muted"
                                    },
                                    "location":"1,1",
                                    "name":"lbl_greeting",
                                    "typeName":"bootstrapcomponents-datalabel",
                                    "typeid":47,
                                    "uuid":"7BA4998A-8E39-589E-B317-576763EE38FB"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"1C093B0F-BBD7-56DF-867E-B194C6D89B4F"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"8FCF5B58-B8CB-5FFE-A60E-0B866CCFDC89"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-md-6 col-xl-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"kpi-card kpi-green"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-user-check",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"kpi-label",
                                                "text":"Checked in today"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"EC0E61C8-37D4-5F4E-AFA8-B279E08BC1F0"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"inToday",
                                                "format":"#0",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "styleClass":"kpi-value"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_inToday",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"B623FBF7-D6FC-53E2-9E8E-7AC6415601A0"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"88BDDBC0-B362-529F-8855-AB3335A547A6"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"CF2C9B5B-927D-5AB5-A63F-F2610FDC257A"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-md-6 col-xl-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"kpi-card kpi-amber"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-user-clock",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"kpi-label",
                                                "text":"Late today"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"6BE080FB-FB4B-5F2B-A258-B8B8F57C74DF"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"lateToday",
                                                "format":"#0",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "styleClass":"kpi-value"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_lateToday",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"760087FD-2D2C-5110-B6C9-5B464491F32B"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"2E8DCD38-8173-5C65-9BD3-A21C3FAC99A3"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"5C4EE6D4-3337-54D0-960F-6DEAB8C1A889"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-md-6 col-xl-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"kpi-card kpi-slate"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-hourglass-half",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"kpi-label",
                                                "text":"Not in yet"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"A9DD3947-C22A-590B-9739-945B6DC4329E"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"notInToday",
                                                "format":"#0",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "styleClass":"kpi-value"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_notInToday",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"D127796A-FC01-55F2-8647-B53156B2F602"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"C499D15C-6B2C-5DB8-A68C-185B448E1D55"
                                }
                            ],
                            "location":"3,3",
                            "typeid":46,
                            "uuid":"8BD5811B-2D58-597D-BF13-35B7AAA1B4DB"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-md-6 col-xl-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"kpi-card kpi-purple"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-plane-departure",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"kpi-label",
                                                "text":"On leave today"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"1B0FBD3C-56B3-5151-B5E5-58C7D86437C7"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"onLeaveToday",
                                                "format":"#0",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "styleClass":"kpi-value"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_onLeaveToday",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"6FFB10F4-E671-5D90-8E40-A2C1194BD1E6"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"5448196B-D26B-5B4D-9A29-0F9D76471F6D"
                                }
                            ],
                            "location":"4,4",
                            "typeid":46,
                            "uuid":"86514739-89BA-5CA0-A9ED-92FC68604DDC"
                        }
                    ],
                    "location":"3,3",
                    "typeid":46,
                    "uuid":"D0D34F2E-E8AF-56AE-8049-59529112BE2C"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-5"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Today"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"A8B71BBF-29A1-59DB-A52A-DA8E7D3E2E7E"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"todayChart",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "showAs":"trusted_html",
                                                "styleClass":"chart-host"
                                            },
                                            "location":"2,2",
                                            "name":"chart_today",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"DFE416D5-9C69-5F50-95DB-AF06673F0A7F"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"BE1B8A79-FA16-5E14-972F-14606AAE41D9"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"9AC25824-E607-5429-8D89-DE17FBFFD630"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-7"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Last 7 days"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"C89A24D4-2A65-57AD-9A68-C915A3DBE7FB"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"weekChart",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "showAs":"trusted_html",
                                                "styleClass":"chart-host"
                                            },
                                            "location":"2,2",
                                            "name":"chart_week",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"DEEC74DD-F3D8-52D5-AD0B-66E9B4FC40DD"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"A2F1D574-8C48-5618-AFB3-507F5C39A9F6"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"1EE8E385-88F3-5305-8FD6-1BD858B449AA"
                        }
                    ],
                    "location":"4,4",
                    "typeid":46,
                    "uuid":"76B2903B-32A3-550D-B28D-4701FCAD767E"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"section-title",
                                        "text":"Organisation"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"9A302B6E-145C-5A1E-966C-4973AB123B90"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"492EFDB1-63DB-5152-AF63-F0E41CDB93BC"
                        }
                    ],
                    "location":"5,5",
                    "typeid":46,
                    "uuid":"1F9B0176-81EC-5F63-B93E-7B79D6993D35"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-md-6 col-xl-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"kpi-card kpi-brand"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-users",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"kpi-label",
                                                "text":"Active employees"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"D94847D1-D8DD-571E-BB68-16AB58EFD61A"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"activeEmployees",
                                                "format":"#0",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "styleClass":"kpi-value"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_activeEmployees",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"F8140AEB-B965-5B08-A96D-3D00358EF8BF"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"D658AB99-222B-5BBD-8206-CA3A46DDBC37"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"9E89D1FB-3D3C-52E2-BB93-3C6520999D67"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-md-6 col-xl-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"kpi-card kpi-brand"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-sitemap",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"kpi-label",
                                                "text":"Departments"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"18DA8CB4-DE78-52D4-807E-222903CC373E"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"departmentCount",
                                                "format":"#0",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "styleClass":"kpi-value"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_departmentCount",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"305123C6-F321-5520-A3B3-47252D9A50CD"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"F573E9D0-46EF-576E-BE5A-EF95F2CCD79F"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"FE643D59-4F20-5AE1-868F-7BDC7C458CD4"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-md-6 col-xl-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"kpi-card kpi-brand"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-clock",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"kpi-label",
                                                "text":"Active shifts"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"720874EF-F090-58EE-BC4E-DF0BF246F6D6"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"shiftCount",
                                                "format":"#0",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "styleClass":"kpi-value"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_shiftCount",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"4AAAB20B-0935-5C91-B10F-B0C92E82712E"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"4C5EFF64-528F-5D0F-8F79-41D7073ECB43"
                                }
                            ],
                            "location":"3,3",
                            "typeid":46,
                            "uuid":"1BE1FCD2-4F82-56D0-BF3E-4CCEC2B47EF0"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-md-6 col-xl-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"kpi-card kpi-brand"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-inbox",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"kpi-label",
                                                "text":"Pending leave requests"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"531F9474-D2D8-5CA5-BAD4-CC554E8B6F4A"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"pendingLeaves",
                                                "format":"#0",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "styleClass":"kpi-value"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_pendingLeaves",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"EF6D9E16-7EFC-51E9-9D41-7E209D2FA130"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"94602985-5B23-5C09-BE5C-B72AB9410454"
                                }
                            ],
                            "location":"4,4",
                            "typeid":46,
                            "uuid":"96E39114-D996-5E88-BF81-8565A348DC4E"
                        }
                    ],
                    "location":"6,6",
                    "typeid":46,
                    "uuid":"B8CACA7F-CE8D-54EF-BBCA-09A5EE63ECFC"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"FFA72FB7-A720-527C-B71B-05FABA7F7DD0"
        }
    ],
    "name":"dashboard",
    "navigatorID":"-1",
    "onShowMethodID":"82063A4F-D373-5FBC-89E8-2E821D2C4541",
    "typeid":3,
    "uuid":"6FC79739-74B5-531D-A970-C5EB90EE676A"
}