{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/departments",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-sitemap",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Departments"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"C3DFBEE5-3B2C-5B84-9F29-65A2D85D47CA"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"152935FD-3BF5-5471-8F77-6036F5EAF381"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"503E3CE0-C8EE-55B3-A105-8A29ECE5097B"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-7"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"grid-toolbar"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"div"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "json":{
                                                        "location":{
                                                            "x":1,
                                                            "y":1
                                                        },
                                                        "styleClass":"card-title",
                                                        "text":"Departments"
                                                    },
                                                    "location":"1,1",
                                                    "typeName":"bootstrapcomponents-label",
                                                    "typeid":47,
                                                    "uuid":"44A226AA-5C94-53F4-BB2B-26F9969D75F5"
                                                },
                                                {
                                                    "json":{
                                                        "imageStyleClass":"fa fa-file-excel",
                                                        "location":{
                                                            "x":2,
                                                            "y":2
                                                        },
                                                        "onActionMethodID":"4A11A6B7-52E5-5B52-BF99-6C4C3B8FE079",
                                                        "styleClass":"btn btn-sm btn-outline-secondary",
                                                        "text":"Export",
                                                        "toolTipText":"Download as CSV (opens in Excel)"
                                                    },
                                                    "location":"2,2",
                                                    "name":"btn_export",
                                                    "typeName":"bootstrapcomponents-button",
                                                    "typeid":47,
                                                    "uuid":"D90B944F-1104-5A05-B532-EF3CE4DF3396"
                                                }
                                            ],
                                            "location":"1,1",
                                            "typeid":46,
                                            "uuid":"B44D75BC-EA9B-5B2E-BC6C-4D55225FF9C8"
                                        },
                                        {
                                            "json":{
                                                "columns":[
                                                    {
                                                        "dataprovider":"code",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Code",
                                                        "minWidth":110,
                                                        "svyUUID":"7F33F82F-3647-595D-AC36-6537283EFE16"
                                                    },
                                                    {
                                                        "dataprovider":"name",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Name",
                                                        "minWidth":110,
                                                        "svyUUID":"275C2419-DCAA-54A8-92D4-162226708949"
                                                    },
                                                    {
                                                        "dataprovider":"manager_employee_id",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Manager",
                                                        "minWidth":110,
                                                        "svyUUID":"E21B9072-4112-509A-9EF7-D420EA888DDF",
                                                        "valuelist":"1878CB17-9579-5E12-9933-F3B964B5551E"
                                                    },
                                                    {
                                                        "dataprovider":"is_active",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Active",
                                                        "minWidth":110,
                                                        "svyUUID":"BF04210A-02A2-5091-9073-8A6590C3CB4B",
                                                        "valuelist":"097FA9DA-DE6C-5D6D-855D-115609AA2E1B"
                                                    }
                                                ],
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "myFoundset":{
                                                    "foundsetSelector":""
                                                },
                                                "readOnly":true,
                                                "responsiveHeight":450,
                                                "rowHeight":32
                                            },
                                            "location":"2,2",
                                            "name":"grid",
                                            "typeName":"aggrid-groupingtable",
                                            "typeid":47,
                                            "uuid":"F25B2979-0651-5B1A-89FE-62B9DAE945CB"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"2602CC9A-3724-5099-B335-4B1F7B10FDAE"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"54A0FDC7-2A9C-5848-B034-F06655C9DA15"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-5"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Details"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"819F748B-23C3-5F94-B614-3B3278640CD2"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_code",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Code"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"0941E0A3-A537-5A05-AAF8-4E94BE62672E"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"code",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"e.g. HR",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_code",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"CD6674E6-BA23-53CA-AD5D-904AB36F6D4E"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"F11D5D26-D2B3-5CB5-A98E-D4FBE47C453A"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-8 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_name",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Name"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"73E77C30-F3F4-5DF0-8A6A-53D084611069"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"name",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Department name",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_name",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"6E972E4A-56ED-5B2A-910C-219D34F8939B"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"336C88DE-0D47-5D13-A89B-BAB5D253EE3F"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"246DC210-74B2-58A5-9C03-46B670BB4561"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_manager",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Manager"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"FF840BD0-45AD-5DB1-B853-FCC0FEE5BA23"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"manager_employee_id",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Select manager",
                                                                "valuelistID":"1878CB17-9579-5E12-9933-F3B964B5551E"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_manager",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"F6E8DECB-640D-5A70-8987-760132A5EB88"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"C48ABDC1-1F40-5F01-AC16-9BC5FDADF585"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"7A14B66D-A1BC-555B-9B6F-AC6F33088C1E"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_active",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Status"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"E1AB8BEB-4076-5A92-9C40-EDCA3A70E3E0"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"is_active",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Active"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_active",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"FE20FE03-1158-541D-B87A-F1F7092BE631"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"A6BA2DEE-879E-55EE-8F0F-132357E5898D"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"D596E2D0-CDCF-5082-8261-965652521EE1"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3 crud-buttons"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-plus",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "onActionMethodID":"AC4657D5-3138-5DBD-80DD-B465B9CA75A4",
                                                                "styleClass":"btn btn-outline-primary me-2",
                                                                "text":"New"
                                                            },
                                                            "location":"1,1",
                                                            "name":"btn_new",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"E178D14E-B06B-5416-82A3-19663590A519"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-save",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"85B0A90D-18FD-58BE-86B8-F6D2D2CBC7D2",
                                                                "styleClass":"btn btn-primary me-2",
                                                                "text":"Save"
                                                            },
                                                            "location":"2,2",
                                                            "name":"btn_save",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"C19948D5-592B-584F-A71D-EB861CE4C9F4"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-undo",
                                                                "location":{
                                                                    "x":3,
                                                                    "y":3
                                                                },
                                                                "onActionMethodID":"BC0B1A83-FD4F-53F6-B1DC-C3589314046C",
                                                                "styleClass":"btn btn-outline-secondary me-2",
                                                                "text":"Cancel"
                                                            },
                                                            "location":"3,3",
                                                            "name":"btn_cancel",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"88D488C2-9F2E-57EA-A7EC-82E238EE03C9"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-trash",
                                                                "location":{
                                                                    "x":4,
                                                                    "y":4
                                                                },
                                                                "onActionMethodID":"BC5B9D04-1A7D-5BBF-BFD6-F0D8A39923AC",
                                                                "styleClass":"btn btn-outline-danger",
                                                                "text":"Delete"
                                                            },
                                                            "location":"4,4",
                                                            "name":"btn_delete",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"9584A0C3-9314-5AA8-BAD2-9BB6D4BD7492"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"B9589799-1EE4-53E9-A66C-141C062D50B0"
                                                }
                                            ],
                                            "location":"5,5",
                                            "typeid":46,
                                            "uuid":"8A8139E2-A783-5AD3-BDC1-5C0A3656DF5E"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"D97DAAC7-A4F1-58CB-8B44-C95A89C1C586"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"FD47815A-E50C-57B8-A907-2D72EF474F9D"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"6B34F142-BA7D-530B-9C05-E23D3F4A8EB4"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"B0BC913F-6910-590E-BAAC-196058A57E5F"
        }
    ],
    "name":"departments",
    "navigatorID":"-1",
    "onLoadMethodID":"1F14C7CD-E671-55E1-9D52-6D0912AB9C49",
    "onShowMethodID":"6412D9B0-2B01-51E7-9934-B58943E60F00",
    "typeid":3,
    "uuid":"F2217518-ECEA-5A4E-A524-F1188620E72A"
}