{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/employee_shift_assignments",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"grid-toolbar"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"div"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "json":{
                                                        "location":{
                                                            "x":1,
                                                            "y":1
                                                        },
                                                        "styleClass":"card-title",
                                                        "text":"Assignments"
                                                    },
                                                    "location":"1,1",
                                                    "typeName":"bootstrapcomponents-label",
                                                    "typeid":47,
                                                    "uuid":"6D947F5E-8246-518E-BE6B-E4CC21800702"
                                                },
                                                {
                                                    "json":{
                                                        "imageStyleClass":"fa fa-file-excel",
                                                        "location":{
                                                            "x":2,
                                                            "y":2
                                                        },
                                                        "onActionMethodID":"D3C2289A-623A-59F2-B5DC-F32E8C6D1F57",
                                                        "styleClass":"btn btn-sm btn-outline-secondary",
                                                        "text":"Export",
                                                        "toolTipText":"Download as CSV (opens in Excel)"
                                                    },
                                                    "location":"2,2",
                                                    "name":"btn_export",
                                                    "typeName":"bootstrapcomponents-button",
                                                    "typeid":47,
                                                    "uuid":"82576A33-B8AD-5495-992D-C9888AC4EEC4"
                                                }
                                            ],
                                            "location":"1,1",
                                            "typeid":46,
                                            "uuid":"60855453-DABF-5B66-8EF0-EA8BC5BF18D0"
                                        },
                                        {
                                            "json":{
                                                "columns":[
                                                    {
                                                        "dataprovider":"shift_id",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Fixed shift",
                                                        "minWidth":110,
                                                        "svyUUID":"129A5B13-02BF-5AEC-9C43-BF259D0CECB0",
                                                        "valuelist":"EB21EBB8-FA70-546E-8D0D-6621F7B072B5"
                                                    },
                                                    {
                                                        "dataprovider":"pattern_id",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Rotating pattern",
                                                        "minWidth":110,
                                                        "svyUUID":"7524DEE1-0B89-5E07-888B-7D46B7C9CA4D",
                                                        "valuelist":"3FA368E2-C4CD-5047-84DF-C9D1E4B70535"
                                                    },
                                                    {
                                                        "dataprovider":"start_date",
                                                        "filterType":"TEXT",
                                                        "format":"dd-MM-yyyy",
                                                        "headerTitle":"From",
                                                        "minWidth":110,
                                                        "svyUUID":"673C934A-89FE-5219-B7E0-C25192B8EDD2"
                                                    },
                                                    {
                                                        "dataprovider":"end_date",
                                                        "filterType":"TEXT",
                                                        "format":"dd-MM-yyyy",
                                                        "headerTitle":"To",
                                                        "minWidth":110,
                                                        "svyUUID":"4FCB8F01-34E2-50A2-9492-E559103C3851"
                                                    },
                                                    {
                                                        "dataprovider":"weekly_off_days",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Weekly off",
                                                        "minWidth":110,
                                                        "svyUUID":"FF42692D-9FDD-51A3-B210-026140D7B707"
                                                    }
                                                ],
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "myFoundset":{
                                                    "foundsetSelector":""
                                                },
                                                "readOnly":true,
                                                "responsiveHeight":300,
                                                "rowHeight":32
                                            },
                                            "location":"2,2",
                                            "name":"grid",
                                            "typeName":"aggrid-groupingtable",
                                            "typeid":47,
                                            "uuid":"1F413A60-B229-5B31-AECB-0F70ECA178E5"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"41F66CF6-072D-5612-A8AB-82AB614FCD04"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"8F719CC7-50C0-5E71-A4CE-C7C261A44741"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"F9BC65E3-DD8C-5ED2-9769-8E1847581345"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Details"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"B58EE765-843A-547F-BF4E-ED69E563D80C"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_shift",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Fixed shift"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"BA223CF0-E7DA-53C6-8D35-1423BC26F71A"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"shift_id",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Select shift",
                                                                "valuelistID":"EB21EBB8-FA70-546E-8D0D-6621F7B072B5"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_shift",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"1CCC3657-8653-52DD-B797-3D48E02EB3F2"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"2417A2C5-5923-59E6-A992-FAD0BF07A9C5"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_pattern",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"or rotating pattern"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"241DE197-4091-51AB-82D8-D9D4D2063F74"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"pattern_id",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Select pattern",
                                                                "valuelistID":"3FA368E2-C4CD-5047-84DF-C9D1E4B70535"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_pattern",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"D674CE42-0C4E-5EC5-9ADB-F0AE8CCFB50B"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"83E6E330-E36F-5EF9-9F90-8FDE055DE926"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_off",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Weekly off days"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"C3174EFE-F54B-5B15-BA77-BB36ACA8CDF5"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"weekly_off_days",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"7 = Sun, 6,7 = Sat+Sun",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_off",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"ACC6091A-F10E-5047-B08F-A4E2C4FDA4A3"
                                                        }
                                                    ],
                                                    "location":"3,3",
                                                    "typeid":46,
                                                    "uuid":"A8139D53-4E52-5CF8-87FD-1AE814236CDC"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"4ABCFB8F-DC05-527E-8B0C-A3F61FDFB144"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_start",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"From"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"F8E3F374-B33D-5E84-A71F-5EE49E548BF0"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"start_date",
                                                                "format":"dd-MM-yyyy",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_start",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"33EFA096-845B-5F5A-B147-3200C4B51CD4"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"9C023DFA-DB1C-5B94-97B0-45946819D65F"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_end",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"To (blank = ongoing)"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"D8D022A1-6CC4-5CEB-8A82-D9271C32164A"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"end_date",
                                                                "format":"dd-MM-yyyy",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_end",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"8971DFD5-496B-5848-8660-98BAFEFF95CD"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"BE680D91-5362-5D42-BE48-E6A5793D484D"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_cycle",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Pattern day 1 falls on"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"71D0A564-AAC1-5DEB-9CFE-6DC3A55FF673"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"cycle_start_date",
                                                                "format":"dd-MM-yyyy",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_cycle",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"601490BB-DF31-554F-8C48-A3EBC7BA947E"
                                                        }
                                                    ],
                                                    "location":"3,3",
                                                    "typeid":46,
                                                    "uuid":"CE0E310E-D82F-5A60-90C0-F8157D676CE0"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"CE8B985C-EFF9-5A27-BFF7-75AE4F2D3159"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3 crud-buttons"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-plus",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "onActionMethodID":"8705147B-B9B8-59C7-BD67-A02E969434EB",
                                                                "styleClass":"btn btn-outline-primary me-2",
                                                                "text":"New"
                                                            },
                                                            "location":"1,1",
                                                            "name":"btn_new",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"68BF6809-9DF9-5FF6-B57A-CAEAA0E36FD9"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-save",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"4F315CE7-BA19-5C1D-84F9-A6ED65B96873",
                                                                "styleClass":"btn btn-primary me-2",
                                                                "text":"Save"
                                                            },
                                                            "location":"2,2",
                                                            "name":"btn_save",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"CADC5B77-6C78-55C7-8D84-988B4CE68934"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-undo",
                                                                "location":{
                                                                    "x":3,
                                                                    "y":3
                                                                },
                                                                "onActionMethodID":"0CD61186-D8F8-5CD3-9F69-A936CE6B02A5",
                                                                "styleClass":"btn btn-outline-secondary me-2",
                                                                "text":"Cancel"
                                                            },
                                                            "location":"3,3",
                                                            "name":"btn_cancel",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"78DDEC42-D29F-56CE-8875-B27949BDC8E3"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-trash",
                                                                "location":{
                                                                    "x":4,
                                                                    "y":4
                                                                },
                                                                "onActionMethodID":"2A66FB95-1D5F-54A6-935B-36C6E101CD46",
                                                                "styleClass":"btn btn-outline-danger",
                                                                "text":"Delete"
                                                            },
                                                            "location":"4,4",
                                                            "name":"btn_delete",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"AE2B62FF-C0DE-5663-8330-56FCAE50ABB9"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"1F76491F-28F3-5DC8-92DB-606EEFEE4686"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"3F7A362F-09C3-57C3-B821-F59239D08B69"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"A348466C-4DD1-5492-AED2-AA3EEBF67DF9"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"8FFB593A-431A-505B-AF7A-179037522A6C"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"78493B58-0F8F-55D9-92D8-711FFAB44C04"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"7BB37CA5-EFAD-5C36-97A6-756544F17210"
        }
    ],
    "name":"employee_shifts",
    "navigatorID":"-1",
    "onLoadMethodID":"485B3965-D5B0-5A26-AA3D-A4918B1B87EC",
    "onShowMethodID":"5561D4F9-EFFF-5668-AE3B-1418F4694B52",
    "typeid":3,
    "uuid":"0A893E6F-4289-5FDD-BAF0-363538814548"
}