{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/employees",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-users",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Employees"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"169D8CCE-3EE5-5844-8387-10F8D1557AE6"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"3DEBC6EE-7882-586A-8097-E89DF0BD4A29"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"F657BF3B-1C34-5666-85FD-39C73E305894"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"card-panel"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"div"
                        }
                    },
                    "items":[
                        {
                            "json":{
                                "location":{
                                    "x":1,
                                    "y":1
                                },
                                "styleClass":"card-title",
                                "text":"Search employees"
                            },
                            "location":"1,1",
                            "typeName":"bootstrapcomponents-label",
                            "typeid":47,
                            "uuid":"E221C430-EB45-5707-874E-FCBED9B215D0"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-4 mb-2"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"form-label",
                                                "text":"Name, code or biometric ID"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"9BE47B20-6AE1-5F02-92FF-482E16999905"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"searchText",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onDataChangeMethodID":"28A86C8D-477F-5CC1-856B-F2BB84040CD7",
                                                "placeholderText":"Type and press Enter",
                                                "styleClass":"form-control"
                                            },
                                            "location":"2,2",
                                            "name":"fld_search",
                                            "typeName":"bootstrapcomponents-textbox",
                                            "typeid":47,
                                            "uuid":"BC2BC696-889C-5D81-B748-C18C7120F5D8"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"1C096ECB-780D-507C-8648-E3AF543A1323"
                                },
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-3 mb-2"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"form-label",
                                                "text":"Department"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"852C17C8-1887-5664-8611-15C60F64F448"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"departmentFilter",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onDataChangeMethodID":"28A86C8D-477F-5CC1-856B-F2BB84040CD7",
                                                "placeholderText":"All",
                                                "valuelistID":"DF1712FB-9977-5A54-AF95-26B2697BC8E7"
                                            },
                                            "location":"2,2",
                                            "name":"fld_department_filter",
                                            "typeName":"bootstrapcomponents-combobox",
                                            "typeid":47,
                                            "uuid":"088FAB16-6BD3-513B-B7C2-8660779C417F"
                                        }
                                    ],
                                    "location":"2,2",
                                    "typeid":46,
                                    "uuid":"D3B41E40-214E-5765-9185-2F13885F3E33"
                                },
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-3 mb-2"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"form-label",
                                                "text":"Designation"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"F6A2A6B0-B462-5A15-954A-891C3CF6A6A8"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"designationFilter",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onDataChangeMethodID":"28A86C8D-477F-5CC1-856B-F2BB84040CD7",
                                                "placeholderText":"All",
                                                "valuelistID":"B91F0193-6DC9-5290-95B5-7EC5A8EBEF6D"
                                            },
                                            "location":"2,2",
                                            "name":"fld_designation_filter",
                                            "typeName":"bootstrapcomponents-combobox",
                                            "typeid":47,
                                            "uuid":"BF8F110F-B63B-5D9D-A78E-A418ACBF7EA6"
                                        }
                                    ],
                                    "location":"3,3",
                                    "typeid":46,
                                    "uuid":"4BC520C0-3499-5097-8303-7CA311088EB3"
                                },
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-2 mb-2"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"form-label",
                                                "text":"Status"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"265DA810-084F-5AF7-8F68-648EA012FCE3"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"statusFilter",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onDataChangeMethodID":"28A86C8D-477F-5CC1-856B-F2BB84040CD7",
                                                "placeholderText":"All",
                                                "valuelistID":"EE5EED5E-06EC-595E-8858-FA29D46AFB0B"
                                            },
                                            "location":"2,2",
                                            "name":"fld_status_filter",
                                            "typeName":"bootstrapcomponents-combobox",
                                            "typeid":47,
                                            "uuid":"F6D33588-829E-5B8C-874D-DA19072E935B"
                                        }
                                    ],
                                    "location":"4,4",
                                    "typeid":46,
                                    "uuid":"7B61A022-CE7D-5EE4-B69E-F4CE57558F7F"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"D4329B90-E859-5042-80F0-0E2061FB3EFC"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-12 filter-actions"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-magnifying-glass",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "onActionMethodID":"83EFDEC8-30DC-5905-956E-AD3E700ABAB4",
                                                "styleClass":"btn btn-primary me-2",
                                                "text":"Search"
                                            },
                                            "location":"1,1",
                                            "name":"btn_search",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"ED77444C-7270-5DEE-A1A4-58BDE546336B"
                                        },
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-eraser",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onActionMethodID":"022E91A1-5AB9-55ED-BEE1-258F0A30F493",
                                                "styleClass":"btn btn-outline-secondary",
                                                "text":"Clear"
                                            },
                                            "location":"2,2",
                                            "name":"btn_clear",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"ED46E50F-E6D6-5052-B80E-9176BFCC3230"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"142332E1-ECE5-556A-903B-85C11F221259"
                                }
                            ],
                            "location":"3,3",
                            "typeid":46,
                            "uuid":"2F4CDF64-CECE-51A5-A587-EEAFFD594812"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"8BFDF526-AD63-5156-90DE-8C8726E2DD28"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"grid-toolbar"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"div"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "json":{
                                                        "location":{
                                                            "x":1,
                                                            "y":1
                                                        },
                                                        "styleClass":"card-title",
                                                        "text":"Employee list"
                                                    },
                                                    "location":"1,1",
                                                    "typeName":"bootstrapcomponents-label",
                                                    "typeid":47,
                                                    "uuid":"8F701759-EE41-57A9-8F62-9439A57DB15A"
                                                },
                                                {
                                                    "json":{
                                                        "imageStyleClass":"fa fa-file-excel",
                                                        "location":{
                                                            "x":2,
                                                            "y":2
                                                        },
                                                        "onActionMethodID":"B2EE7A7D-3315-5A7C-8AD5-4CB864E60169",
                                                        "styleClass":"btn btn-sm btn-outline-secondary",
                                                        "text":"Export",
                                                        "toolTipText":"Download as CSV (opens in Excel)"
                                                    },
                                                    "location":"2,2",
                                                    "name":"btn_export",
                                                    "typeName":"bootstrapcomponents-button",
                                                    "typeid":47,
                                                    "uuid":"53EC2241-4A9C-5148-8F90-2AC5C082C21C"
                                                }
                                            ],
                                            "location":"1,1",
                                            "typeid":46,
                                            "uuid":"339F8E61-A18A-5A61-BAF1-2AA5739B891D"
                                        },
                                        {
                                            "json":{
                                                "columns":[
                                                    {
                                                        "dataprovider":"employee_code",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Code",
                                                        "minWidth":110,
                                                        "svyUUID":"27D11066-8EDC-551C-98FD-48295AA806DF"
                                                    },
                                                    {
                                                        "dataprovider":"first_name",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"First name",
                                                        "minWidth":110,
                                                        "svyUUID":"8D096B27-2930-50E2-BA72-25E2F627DEE2"
                                                    },
                                                    {
                                                        "dataprovider":"last_name",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Last name",
                                                        "minWidth":110,
                                                        "svyUUID":"45EB7B11-9174-5638-9633-68CB3A02D023"
                                                    },
                                                    {
                                                        "dataprovider":"department_id",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Department",
                                                        "minWidth":110,
                                                        "svyUUID":"B61ED216-27F1-547B-A924-E89C3F55DFCC",
                                                        "valuelist":"DF1712FB-9977-5A54-AF95-26B2697BC8E7"
                                                    },
                                                    {
                                                        "dataprovider":"designation_id",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Designation",
                                                        "minWidth":110,
                                                        "svyUUID":"EBDEC2CF-1114-50C0-BC58-FD3A6535FED4",
                                                        "valuelist":"B91F0193-6DC9-5290-95B5-7EC5A8EBEF6D"
                                                    },
                                                    {
                                                        "dataprovider":"status",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Status",
                                                        "minWidth":110,
                                                        "svyUUID":"53F9B57C-3EE3-5BE1-B5BD-442230C89A9B",
                                                        "valuelist":"EE5EED5E-06EC-595E-8858-FA29D46AFB0B"
                                                    },
                                                    {
                                                        "dataprovider":"biometric_user_id",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Biometric ID",
                                                        "minWidth":110,
                                                        "svyUUID":"CCD81871-01EF-59A8-A1B4-9A777AF853F6"
                                                    }
                                                ],
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "myFoundset":{
                                                    "foundsetSelector":""
                                                },
                                                "readOnly":true,
                                                "responsiveHeight":300,
                                                "rowHeight":32
                                            },
                                            "location":"2,2",
                                            "name":"grid",
                                            "typeName":"aggrid-groupingtable",
                                            "typeid":47,
                                            "uuid":"046FECCE-FEA8-51B8-A9EF-D42751ABEE4D"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"9827DBCE-D5EE-5B51-8BB4-2F7064635F63"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"561E870B-368A-550F-87AB-69E2B9CC2615"
                        }
                    ],
                    "location":"3,3",
                    "typeid":46,
                    "uuid":"42BA1E51-D12D-5A81-B8F9-16E1D224D51A"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Details"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"5145DFD3-21B3-5E4A-8E29-F6389A1AFAAE"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-3 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_code",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Employee code"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"A7BD5EE2-3833-5254-9E82-39798C6F92E2"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"employee_code",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"e.g. EMP001",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_code",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"1A8941DA-2B99-54F7-A383-4760B1BE317A"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"ADFF84A8-D91D-5476-B6D4-180A024EA425"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-3 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_first",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"First name"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"4CCE654F-8B82-5D45-B69E-7C2FE48491E3"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"first_name",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_first",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"96729B31-79C1-52E9-9C94-2A74D2F733FB"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"3EC93CAC-7D84-5CB4-9652-86060560EF96"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-3 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_last",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Last name"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"911C7B2B-23B8-590D-8221-A65413E5CA7E"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"last_name",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_last",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"EDDAFFB3-966B-5FC6-92F5-2495B4923E14"
                                                        }
                                                    ],
                                                    "location":"3,3",
                                                    "typeid":46,
                                                    "uuid":"44197F70-0C95-5D4F-922C-186808922F69"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-3 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_status",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Status"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"A3639FFE-E171-578D-97E9-30A350A6C57B"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"status",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "valuelistID":"EE5EED5E-06EC-595E-8858-FA29D46AFB0B"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_status",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"3A9F42F8-38E7-53D5-82B5-6DEA149B5356"
                                                        }
                                                    ],
                                                    "location":"4,4",
                                                    "typeid":46,
                                                    "uuid":"89D0E2DE-6DD9-50AF-B038-94F26281B5B3"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"F5923AE3-BCC0-5999-98DE-9741389E79BA"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-3 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_department",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Department"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"1F8ECFFD-3256-57A0-8397-587BD90B4677"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"department_id",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Select department",
                                                                "valuelistID":"DF1712FB-9977-5A54-AF95-26B2697BC8E7"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_department",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"FC80CE19-3B81-5268-B82A-FCAC3B5A578A"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"630CC632-CBB7-59AC-835C-520A86A11AB3"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-3 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_designation",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Designation"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"924DF233-ED95-5ED5-B64D-64380D60BF67"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"designation_id",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Select designation",
                                                                "valuelistID":"B91F0193-6DC9-5290-95B5-7EC5A8EBEF6D"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_designation",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"369A7BAF-DCF3-5BD9-B21F-D40EE6A20CF9"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"44719D39-CA31-5C56-9C70-29BFFDDF9172"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-3 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_reports_to",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Reports to (manager)"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"6E36AE08-B365-5D7F-8C29-535552264366"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"reports_to_employee_id",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Select manager",
                                                                "valuelistID":"1878CB17-9579-5E12-9933-F3B964B5551E"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_reports_to",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"410A6D1A-433D-5CDE-B6B4-A4872755F77D"
                                                        }
                                                    ],
                                                    "location":"3,3",
                                                    "typeid":46,
                                                    "uuid":"1512E48D-0598-5367-B5D0-208841913DC3"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-3 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_biometric",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Biometric ID (on device)"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"D1A2ABC7-92A0-535B-A005-3680B93D2FC0"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"biometric_user_id",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"e.g. 1001",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_biometric",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"E5B8990E-DD05-5015-8B61-BA58F2F3008C"
                                                        }
                                                    ],
                                                    "location":"4,4",
                                                    "typeid":46,
                                                    "uuid":"75EA5382-9149-5F09-B920-7F0718A9ECAF"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"1C8D1649-2B14-5A76-9004-802A101D883F"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_email",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Email"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"C5937F63-9BC4-5861-876D-C30E3752A635"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"email",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"name@company.com",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_email",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"9D2B6926-EEE4-56D0-946C-9273E93ED4BE"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"C8FE09A1-EEF4-5DFA-8E09-52A2D0E9BF87"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_phone",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Phone"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"A7B22601-8219-59D7-B83D-A8C99506F3C3"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"phone",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_phone",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"86A25D67-C869-54F2-9A55-1FC8F8578330"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"63DC69E3-23F2-5987-8799-33DCDCFD7AEE"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_gender",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Gender"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"867B1872-7C20-5DD4-B6C0-5FB8765FB64F"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"gender",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "valuelistID":"E5893EE7-BE56-5476-98F1-746883059989"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_gender",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"3660CF11-7053-5B8B-AD72-0D12220A3FA2"
                                                        }
                                                    ],
                                                    "location":"3,3",
                                                    "typeid":46,
                                                    "uuid":"69CEE513-BCED-562C-ACE7-745641B4B06D"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"5BDA6568-7998-50E6-B2EA-8296DD578DD1"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_dob",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Date of birth"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"D979453E-8FBC-5DE0-9D65-2671DC96F0E0"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"date_of_birth",
                                                                "format":"dd-MM-yyyy",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_dob",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"6BB75F5C-A2FF-5F8B-AB13-1075EA776533"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"D47BA216-0D0E-520C-B824-8BA0F2268FC5"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_join",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Join date"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"3887DCDF-F7A7-5327-92F6-DD735DA2D127"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"join_date",
                                                                "format":"dd-MM-yyyy",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_join",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"2BD1FA13-1A55-5EC3-AA01-BB766861CCA1"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"FBE64400-136A-53B7-80C0-42143EEF7728"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_leave",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Leave date"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"9B03953E-8CC0-52F6-B83C-E24D967F1B4F"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"leave_date",
                                                                "format":"dd-MM-yyyy",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_leave",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"08AF74B3-1D02-5675-8E8A-5AEE017FE11D"
                                                        }
                                                    ],
                                                    "location":"3,3",
                                                    "typeid":46,
                                                    "uuid":"F68C1CB9-7732-5D4F-89E7-6965AC7D374E"
                                                }
                                            ],
                                            "location":"5,5",
                                            "typeid":46,
                                            "uuid":"5DCF1810-4DED-5374-982E-25D6C6242D69"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3 crud-buttons"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-plus",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "onActionMethodID":"09E0C21F-10BF-52B1-9979-132B482D25E1",
                                                                "styleClass":"btn btn-outline-primary me-2",
                                                                "text":"New"
                                                            },
                                                            "location":"1,1",
                                                            "name":"btn_new",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"ADDC91E3-C844-5833-A666-5F239320466E"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-save",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"67C79C50-AFEF-5615-B45D-C39ECC958344",
                                                                "styleClass":"btn btn-primary me-2",
                                                                "text":"Save"
                                                            },
                                                            "location":"2,2",
                                                            "name":"btn_save",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"52BCF796-E097-535C-9F8F-5D44721BC412"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-undo",
                                                                "location":{
                                                                    "x":3,
                                                                    "y":3
                                                                },
                                                                "onActionMethodID":"CD1FC566-97B6-5469-BC09-1FC7861914D3",
                                                                "styleClass":"btn btn-outline-secondary me-2",
                                                                "text":"Cancel"
                                                            },
                                                            "location":"3,3",
                                                            "name":"btn_cancel",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"30D9FBB1-E6C7-549E-BBF3-82C91A443BCA"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-trash",
                                                                "location":{
                                                                    "x":4,
                                                                    "y":4
                                                                },
                                                                "onActionMethodID":"0CEA12AE-FC32-5223-BB36-69342320F039",
                                                                "styleClass":"btn btn-outline-danger",
                                                                "text":"Delete"
                                                            },
                                                            "location":"4,4",
                                                            "name":"btn_delete",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"2C4428B8-328D-581F-96E8-DCF6C00B7AF3"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"199C22E0-6DE3-5A4F-9CC0-3B4D4489AF2C"
                                                }
                                            ],
                                            "location":"6,6",
                                            "typeid":46,
                                            "uuid":"43E4A553-ED28-5F1A-B472-1F1BE4B3C7CF"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"A1BFEBB7-8B66-5697-8909-FA91B244489D"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"236F0274-B48C-5826-B0D7-3EE46A0FB29B"
                        }
                    ],
                    "location":"4,4",
                    "typeid":46,
                    "uuid":"ABC36E2E-8AF9-5741-8EDD-1DAA7BE43840"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Shift assignment"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"87F5F897-BDFF-5B5C-8C33-414D599319F8"
                                        },
                                        {
                                            "json":{
                                                "containedForm":"0A893E6F-4289-5FDD-BAF0-363538814548",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "relationName":"employees_to_employee_shift_assignments"
                                            },
                                            "location":"2,2",
                                            "name":"shifts_container",
                                            "typeName":"servoycore-formcontainer",
                                            "typeid":47,
                                            "uuid":"31498F2E-7FC4-51B1-A2A2-220E4FCA092D"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"ACCA9CA0-E333-57AC-A306-EA2F54648224"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"DDBCB9F1-8AF8-5BB8-926B-42F1B988FAC9"
                        }
                    ],
                    "location":"5,5",
                    "typeid":46,
                    "uuid":"4E384628-CF99-53F7-A551-B6496EDCBD07"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"D4A9302B-666A-5C5E-8CB0-7A9A06E6C443"
        }
    ],
    "name":"employees",
    "navigatorID":"-1",
    "onLoadMethodID":"D101633F-A3DE-51B2-AFF7-6CF116BF7803",
    "onShowMethodID":"F82D05C3-708A-5265-8AA2-1A1A28E0A00F",
    "typeid":3,
    "uuid":"E32520B0-AEFB-534F-9880-853EC5EB913B"
}