{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/holidays",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-umbrella-beach",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Holidays"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"9087FD95-364C-5E07-9B5E-D066A62FFFA2"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"E217B5DA-F2CC-54E5-8DDA-65D156E45075"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"CC3D6428-9A4F-5168-99A9-0B8FD8D23518"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-7"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"grid-toolbar"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"div"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "json":{
                                                        "location":{
                                                            "x":1,
                                                            "y":1
                                                        },
                                                        "styleClass":"card-title",
                                                        "text":"Holidays"
                                                    },
                                                    "location":"1,1",
                                                    "typeName":"bootstrapcomponents-label",
                                                    "typeid":47,
                                                    "uuid":"2182F695-E30A-596E-A216-12784529A7CF"
                                                },
                                                {
                                                    "json":{
                                                        "imageStyleClass":"fa fa-file-excel",
                                                        "location":{
                                                            "x":2,
                                                            "y":2
                                                        },
                                                        "onActionMethodID":"4ADC88FC-1148-5BAC-9859-CB791BF751AD",
                                                        "styleClass":"btn btn-sm btn-outline-secondary",
                                                        "text":"Export",
                                                        "toolTipText":"Download as CSV (opens in Excel)"
                                                    },
                                                    "location":"2,2",
                                                    "name":"btn_export",
                                                    "typeName":"bootstrapcomponents-button",
                                                    "typeid":47,
                                                    "uuid":"36EB3043-B4D4-579D-98DA-D6B43398673E"
                                                }
                                            ],
                                            "location":"1,1",
                                            "typeid":46,
                                            "uuid":"262A101C-7B6F-578A-87A1-08ACAAF182C8"
                                        },
                                        {
                                            "json":{
                                                "columns":[
                                                    {
                                                        "dataprovider":"holiday_date",
                                                        "filterType":"TEXT",
                                                        "format":"EEE dd-MM-yyyy",
                                                        "headerTitle":"Date",
                                                        "minWidth":110,
                                                        "svyUUID":"BDB4BC16-2536-517C-9B1F-D63C20D0DA0A"
                                                    },
                                                    {
                                                        "dataprovider":"name",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Holiday",
                                                        "minWidth":110,
                                                        "svyUUID":"2A79F360-6175-58FC-8F7F-26A08A123B3A"
                                                    },
                                                    {
                                                        "dataprovider":"is_optional",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Optional",
                                                        "minWidth":110,
                                                        "svyUUID":"B69B0019-46CE-58AC-BF06-7A71A205A14C",
                                                        "valuelist":"097FA9DA-DE6C-5D6D-855D-115609AA2E1B"
                                                    }
                                                ],
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "myFoundset":{
                                                    "foundsetSelector":""
                                                },
                                                "readOnly":true,
                                                "responsiveHeight":450,
                                                "rowHeight":32
                                            },
                                            "location":"2,2",
                                            "name":"grid",
                                            "typeName":"aggrid-groupingtable",
                                            "typeid":47,
                                            "uuid":"D2D5BDE3-D0E1-573F-82B4-F4588CA839CD"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"974951E9-B21D-5821-8B16-FDD90E9567BD"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"850369CF-EC6B-5B8E-B77E-5DB2D76C8AA7"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-5"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Details"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"8EAEE119-5A11-5033-B2DD-1622D344F045"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-5 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_date",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Date"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"6146A5B4-1200-5BAA-8705-6E67EDAF0D38"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"holiday_date",
                                                                "format":"dd-MM-yyyy",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_date",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"28DC27E3-A683-5399-A56F-895CBF1B30C4"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"E52601B5-894A-568E-90DA-F0794B9F89FA"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-7 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_name",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Name"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"86835B76-0B52-59B7-A1FC-E660557F2AA6"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"name",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"e.g. Independence Day",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_name",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"EA92C784-6FC4-5B57-B3F7-9E502D8FBE94"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"D56292E9-7B59-5614-8247-913121283FBE"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"1FA72D29-0684-5CDB-B0E0-516AAC837AD9"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_optional",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Type"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"5CE46FEE-B5AF-5461-847D-CD80ABD41A7A"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"is_optional",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Optional holiday (employees may still work)"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_optional",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"CF48CB05-01DB-5972-9AA7-4641D3166817"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"E53AF779-CBCD-5283-8AD6-A4369E4C7075"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"1A1F0459-F664-52C6-8328-98A0FBE67590"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3 crud-buttons"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-plus",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "onActionMethodID":"5385ACC0-CBAB-552E-B7A8-93435AFD4F5B",
                                                                "styleClass":"btn btn-outline-primary me-2",
                                                                "text":"New"
                                                            },
                                                            "location":"1,1",
                                                            "name":"btn_new",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"F6AF801F-9DF7-5506-9271-1EEED21F64E3"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-save",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"AAFC4B83-EA38-5515-ACA9-985CCF452D0E",
                                                                "styleClass":"btn btn-primary me-2",
                                                                "text":"Save"
                                                            },
                                                            "location":"2,2",
                                                            "name":"btn_save",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"6D2C8CD2-BE60-5730-B783-6DDFCF16EB4A"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-undo",
                                                                "location":{
                                                                    "x":3,
                                                                    "y":3
                                                                },
                                                                "onActionMethodID":"26F009E6-544D-5593-A585-375BA28C95CA",
                                                                "styleClass":"btn btn-outline-secondary me-2",
                                                                "text":"Cancel"
                                                            },
                                                            "location":"3,3",
                                                            "name":"btn_cancel",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"EA6E9051-43DD-518E-A693-5BD54A5DFF4C"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-trash",
                                                                "location":{
                                                                    "x":4,
                                                                    "y":4
                                                                },
                                                                "onActionMethodID":"2B84B7ED-CDD2-5A04-87C8-984EE94C49EE",
                                                                "styleClass":"btn btn-outline-danger",
                                                                "text":"Delete"
                                                            },
                                                            "location":"4,4",
                                                            "name":"btn_delete",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"82429D38-A955-59C2-89C5-D9B04CE173D9"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"3B8B83D4-65EE-580E-B01D-923C7418ABEA"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"16289978-1CD7-56AE-B954-330B89B62D61"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"9B3CD95A-6210-54D7-B156-958327DDD67A"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"6CC8993A-CCD1-5369-83E2-886971D0D36C"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"C2459A19-E70A-5D8D-83D2-9CE0E4AA412A"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"82C80377-77CC-5EB5-96FC-FE7F35031812"
        }
    ],
    "name":"holidays",
    "navigatorID":"-1",
    "onLoadMethodID":"C3FEC314-F6E7-5FE6-AD0B-C4F23FDF109A",
    "onShowMethodID":"24011FA5-73C0-5934-A6BB-C7D660435C8B",
    "typeid":3,
    "uuid":"05CC7641-43FA-5A89-BD13-76B131300795"
}