{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/leave_types",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-plane-departure",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Leave Types"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"0BE53050-27E4-59E3-9EEB-6FC5DCF5D3A2"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"A4712D2E-C34E-55D1-96B0-831FBC1628E9"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"0DEEC0F0-55A9-5B21-8885-73B01B0D4E45"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-6"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"grid-toolbar"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"div"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "json":{
                                                        "location":{
                                                            "x":1,
                                                            "y":1
                                                        },
                                                        "styleClass":"card-title",
                                                        "text":"Leave Types"
                                                    },
                                                    "location":"1,1",
                                                    "typeName":"bootstrapcomponents-label",
                                                    "typeid":47,
                                                    "uuid":"01A5A54C-63E5-56D3-BB26-CF78D985909A"
                                                },
                                                {
                                                    "json":{
                                                        "imageStyleClass":"fa fa-file-excel",
                                                        "location":{
                                                            "x":2,
                                                            "y":2
                                                        },
                                                        "onActionMethodID":"AE17BB9E-1AE6-5718-A44A-C1A758ACAF6B",
                                                        "styleClass":"btn btn-sm btn-outline-secondary",
                                                        "text":"Export",
                                                        "toolTipText":"Download as CSV (opens in Excel)"
                                                    },
                                                    "location":"2,2",
                                                    "name":"btn_export",
                                                    "typeName":"bootstrapcomponents-button",
                                                    "typeid":47,
                                                    "uuid":"FF1884F8-C263-51E8-B665-EA0AD9B47ECF"
                                                }
                                            ],
                                            "location":"1,1",
                                            "typeid":46,
                                            "uuid":"0CE3D921-FE40-58DC-87B1-77241EC522D0"
                                        },
                                        {
                                            "json":{
                                                "columns":[
                                                    {
                                                        "dataprovider":"code",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Code",
                                                        "minWidth":110,
                                                        "svyUUID":"D5282F0D-3F36-5095-B3B6-645B8201E3F8"
                                                    },
                                                    {
                                                        "dataprovider":"name",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Name",
                                                        "minWidth":110,
                                                        "svyUUID":"84E591A6-B23D-579D-94A2-BBDC034727B1"
                                                    },
                                                    {
                                                        "dataprovider":"days_per_year",
                                                        "filterType":"TEXT",
                                                        "format":"#0.##",
                                                        "headerTitle":"Days/year",
                                                        "minWidth":110,
                                                        "svyUUID":"5E8E56E5-7F55-57D9-B0AD-25E632BE4C00"
                                                    },
                                                    {
                                                        "dataprovider":"is_paid",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Paid",
                                                        "minWidth":110,
                                                        "svyUUID":"977C6F7E-934B-5D07-B674-B48880F81318",
                                                        "valuelist":"097FA9DA-DE6C-5D6D-855D-115609AA2E1B"
                                                    },
                                                    {
                                                        "dataprovider":"is_active",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Active",
                                                        "minWidth":110,
                                                        "svyUUID":"CF128BBB-A4BF-5640-92DA-9356514604BF",
                                                        "valuelist":"097FA9DA-DE6C-5D6D-855D-115609AA2E1B"
                                                    }
                                                ],
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "myFoundset":{
                                                    "foundsetSelector":""
                                                },
                                                "readOnly":true,
                                                "responsiveHeight":450,
                                                "rowHeight":32
                                            },
                                            "location":"2,2",
                                            "name":"grid",
                                            "typeName":"aggrid-groupingtable",
                                            "typeid":47,
                                            "uuid":"13CEE29A-0A84-506A-BF1F-26426EDAFB2E"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"7EB2FC6B-BBDD-5F62-9E2C-923597CE2108"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"3BAAA5E6-AD1A-53E3-8A98-E169006FA491"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-6"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Details"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"86F43A3B-493A-5CB4-9470-10189F95F96C"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-5 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_code",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Code"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"5EEE39B1-459F-5B77-AA4F-C03C188A75D4"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"code",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"e.g. ANNUAL",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_code",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"5E741DE1-955D-5A11-A19C-46310BAD5FCA"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"2F607FAE-9230-5A8A-9223-8C410B7D2E96"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-7 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_name",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Name"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"172C4204-00C6-5A75-9F7B-381CEC5BD00A"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"name",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Leave type name",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_name",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"C27AAEDE-FC6A-5D44-8AD2-C61F89F91D21"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"DD953614-E93D-57CE-82E3-DE53414734A1"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"F49ECCAB-EF70-59B9-B8C0-F1DA150D40E9"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_days",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Days per year"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"17B61846-F7F9-5427-91CA-7FC338CB9621"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"days_per_year",
                                                                "format":"#0.##",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_days",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"8434C18C-838C-5821-AD1E-F31C0C621B60"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"220CDBF3-7C0E-590F-92E5-403044285E8C"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_max_cf",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Max carry forward (days)"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"9083EC8D-441B-5EBF-BB35-425DD054B9EE"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"max_carry_forward",
                                                                "format":"#0.##",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_max_cf",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"6F9D310F-2988-54A7-9EEC-931A371B0A60"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"A31999F3-2E8D-582D-8A18-03C263804D26"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"6E8D92E0-99A8-54BD-896C-00FD1326F7C8"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_paid",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Rules"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"EEE86BC1-E1E8-5F08-9C04-9E79C2419D23"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"is_paid",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Paid leave"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_paid",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"32A13CE9-6974-54A8-B684-08EF5AA4BFCE"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"210899D1-BADF-5127-BBA2-3BB7DB4C5B4A"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_cf",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"\u00a0"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"15CD9B69-E767-5199-BC9D-58DBB628C101"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"carry_forward",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Unused days carry forward"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_cf",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"116664BC-E4CE-594D-8514-E4933D2464B5"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"DC16F3A7-1808-5EED-89AF-D88893C9F823"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"230E9017-4C7E-5370-BC9E-7F53694A406C"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_approval",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"\u00a0"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"E8263EED-99C9-5804-9C51-DD072CBE14B0"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"requires_approval",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Requires approval"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_approval",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"1AFAF450-DD50-5449-BF99-C403C48BF2AE"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"96138B72-588B-5590-8974-FA7CB4819BA2"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_half",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"\u00a0"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"36C5735D-8E65-5480-8D23-145F4903D5AF"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"allow_half_day",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Half day allowed"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_half",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"32B0B5BD-ED33-56DE-B5FF-B2036AF958A5"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"D865F765-EDDA-5C89-878D-E8ACC832A594"
                                                }
                                            ],
                                            "location":"5,5",
                                            "typeid":46,
                                            "uuid":"B44DFDA5-7DEE-50D1-BD7E-8B9C902561A7"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_active",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Status"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"CDC73B85-04F6-5CA1-A636-21734A93E5A4"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"is_active",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Active"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_active",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"4DB759C6-577E-5C8E-81BF-541D29E28A23"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"E0F4B350-9D5D-5AA1-8BD4-2AC5944B3A13"
                                                }
                                            ],
                                            "location":"6,6",
                                            "typeid":46,
                                            "uuid":"B5E66BE6-FAAA-5FAE-B51C-5C979E80D96E"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3 crud-buttons"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-plus",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "onActionMethodID":"D66051D5-5FBE-5B8F-8CAC-8A9EA00ACED0",
                                                                "styleClass":"btn btn-outline-primary me-2",
                                                                "text":"New"
                                                            },
                                                            "location":"1,1",
                                                            "name":"btn_new",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"D6DB62E0-6669-55B9-B4D9-1F0EC54B56F0"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-save",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"F456C220-2C89-55BA-8CA0-CFDC00B15C53",
                                                                "styleClass":"btn btn-primary me-2",
                                                                "text":"Save"
                                                            },
                                                            "location":"2,2",
                                                            "name":"btn_save",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"7CDCA994-1566-55BA-9A1E-6CA3AB981E31"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-undo",
                                                                "location":{
                                                                    "x":3,
                                                                    "y":3
                                                                },
                                                                "onActionMethodID":"915BCFE0-71EF-5BF1-B942-B57BB071BADE",
                                                                "styleClass":"btn btn-outline-secondary me-2",
                                                                "text":"Cancel"
                                                            },
                                                            "location":"3,3",
                                                            "name":"btn_cancel",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"6254BE21-E65B-591A-85DD-88867083FF33"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-trash",
                                                                "location":{
                                                                    "x":4,
                                                                    "y":4
                                                                },
                                                                "onActionMethodID":"2A81E062-3E6C-5C27-97B2-4601DF53F42B",
                                                                "styleClass":"btn btn-outline-danger",
                                                                "text":"Delete"
                                                            },
                                                            "location":"4,4",
                                                            "name":"btn_delete",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"6657F66B-5986-55E8-BEAB-DB44295DAE11"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"11B02BD5-D3B2-533C-9652-A7E2CE0E3FE3"
                                                }
                                            ],
                                            "location":"7,7",
                                            "typeid":46,
                                            "uuid":"96052C32-5FC1-5BA7-87DA-15119E222199"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"3BBB7796-61C9-521D-BB3B-09D697711C81"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"EFEDDD17-6EEF-5402-9067-4150C3AB1DD5"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"6F37C954-7A58-5AE6-804E-AD82C046834F"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"215A81E3-B335-5C87-924E-9E7321D7C864"
        }
    ],
    "name":"leave_types",
    "navigatorID":"-1",
    "onLoadMethodID":"79514453-1FA1-56D5-8B54-CBA577485F45",
    "onShowMethodID":"FA1DE970-F1D3-530D-9C8F-282AED1B6A2F",
    "typeid":3,
    "uuid":"218442AA-9C3A-519C-8A69-F203D582C45D"
}