{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid login-page"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row justify-content-center"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-sm-10 col-md-6 col-lg-4"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel login-card"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "dataProviderID":"scopes.settings.appName",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "showAs":"text",
                                                "styleClass":"login-brand"
                                            },
                                            "location":"1,1",
                                            "name":"lbl_app",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"2A252764-5F30-5E21-AF37-795C82AB2F76"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"scopes.settings.companyName",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "showAs":"text",
                                                "styleClass":"login-company"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_company",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"277AB121-8794-5AA5-91AD-3F9A374694E2"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_username",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Username"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"0BFF6792-BF43-5249-AA4E-8C82C7BD4867"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"username",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Username",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_username",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"6805849D-DF5D-56B0-AEE8-C9CBEF9F7A74"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"D0F8BC1C-4B69-54F9-8282-D28B98E87854"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"5C8DA0A7-B1F9-52FC-83E2-FAC81E38D8C6"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_password",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Password"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"2E24E544-7D3C-557A-BDC4-5A9DDAE3B9F8"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"password",
                                                                "inputType":"password",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"180C20FD-3D15-5C7C-B0F2-BF64BA1D0480",
                                                                "placeholderText":"Password",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_password",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"0E11FA0D-0FF8-50B3-B1DB-BDF326AC21A8"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"E24C3250-992C-5D98-82D9-B99A8E7E96D3"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"17AF5AD7-04A3-51F8-904F-A947A317F8B1"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"loginError",
                                                "location":{
                                                    "x":5,
                                                    "y":5
                                                },
                                                "showAs":"text",
                                                "styleClass":"login-error"
                                            },
                                            "location":"5,5",
                                            "name":"lbl_error",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"49C6CF13-EE13-5132-833D-CAB772D72E47"
                                        },
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-right-to-bracket",
                                                "location":{
                                                    "x":6,
                                                    "y":6
                                                },
                                                "onActionMethodID":"180C20FD-3D15-5C7C-B0F2-BF64BA1D0480",
                                                "styleClass":"btn btn-primary w-100",
                                                "text":"Sign in"
                                            },
                                            "location":"6,6",
                                            "name":"btn_login",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"7833E958-1F97-58B2-834E-446BD361441B"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"CD3B8594-CF5B-510E-87C9-55220A3D65D4"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"1669CCC6-30E3-511E-8837-28AAC048056E"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"449ECBDC-F143-51A7-8DBB-2EDA9E536002"
                },
                {
                    "json":{
                        "dataProviderID":"scopes.settings.appName",
                        "location":{
                            "x":2,
                            "y":2
                        },
                        "styleClass":"d-none",
                        "styleClassExpression":"scopes.settings.themeClass"
                    },
                    "location":"2,2",
                    "name":"theme_marker",
                    "typeName":"bootstrapcomponents-datalabel",
                    "typeid":47,
                    "uuid":"CD276223-FA03-544C-B11C-885D77341174"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"1F83F277-BCF9-5DE0-81AB-093A4398187D"
        }
    ],
    "name":"login",
    "navigatorID":"-1",
    "onShowMethodID":"19BE6B22-3EF9-502B-BAC6-D8421DE02D51",
    "typeid":3,
    "uuid":"C278F231-999E-5A25-B561-7E81DCD2E843"
}