{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/attendance",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-calendar-day",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"My Attendance"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"CA6F0F53-3BB0-5525-AA4D-DB5CC2F7F220"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"90F4C5CA-8F68-537A-BA96-D468182AF042"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"A123AE4E-9EB5-5AF3-B60A-9499E6F11C7D"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mb-2"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "dataProviderID":"infoText",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "showAs":"text",
                                        "styleClass":"login-error"
                                    },
                                    "location":"1,1",
                                    "name":"lbl_info",
                                    "typeName":"bootstrapcomponents-datalabel",
                                    "typeid":47,
                                    "uuid":"0A9C102A-A67D-5206-BBD0-940AC246CCF6"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"A60EC33B-B7D8-5706-B545-D1AD49A26745"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"AE14E07C-9866-563E-B4A7-6BCD5CD8D3F4"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"card-panel"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"div"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"grid-toolbar"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"div"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"month-nav"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-chevron-left",
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "onActionMethodID":"F94D2C84-002D-515B-9AD5-ACE85973395C",
                                                "styleClass":"btn btn-sm btn-outline-secondary me-2",
                                                "text":"",
                                                "toolTipText":"Previous month"
                                            },
                                            "location":"1,1",
                                            "name":"btn_prev",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"EAF8FE38-78C9-5B02-A8A4-CD872940C58D"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"monthLabel",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "showAs":"text",
                                                "styleClass":"card-title month-label"
                                            },
                                            "location":"2,2",
                                            "name":"lbl_month",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"C3B765E5-32CB-56C0-AA72-AA47446CC408"
                                        },
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-chevron-right",
                                                "location":{
                                                    "x":3,
                                                    "y":3
                                                },
                                                "onActionMethodID":"56D51F43-5987-5502-A7D3-B6BBCBF4E101",
                                                "styleClass":"btn btn-sm btn-outline-secondary ms-2",
                                                "text":"",
                                                "toolTipText":"Next month"
                                            },
                                            "location":"3,3",
                                            "name":"btn_next",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"BDD7E4DE-D137-5243-9AEE-D6FDA13C0BC2"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"ED195582-6DBF-5994-B222-ACEACAF5CA3A"
                                },
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-file-excel",
                                        "location":{
                                            "x":2,
                                            "y":2
                                        },
                                        "onActionMethodID":"C285469E-7381-515D-A0D1-59C6DFB93400",
                                        "styleClass":"btn btn-sm btn-outline-secondary",
                                        "text":"Export"
                                    },
                                    "location":"2,2",
                                    "name":"btn_export",
                                    "typeName":"bootstrapcomponents-button",
                                    "typeid":47,
                                    "uuid":"D7C07B2F-3F1D-581E-A7BD-1B94F2702796"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"54203C3F-BDD7-5F23-A35F-A33503D97D7D"
                        },
                        {
                            "json":{
                                "dataProviderID":"summaryText",
                                "location":{
                                    "x":2,
                                    "y":2
                                },
                                "showAs":"text",
                                "styleClass":"summary-text d-block mb-2"
                            },
                            "location":"2,2",
                            "name":"lbl_summary",
                            "typeName":"bootstrapcomponents-datalabel",
                            "typeid":47,
                            "uuid":"D2D2EA41-0E95-59EA-BBD7-12B0ED30DE79"
                        },
                        {
                            "json":{
                                "columns":[
                                    {
                                        "dataprovider":"work_date",
                                        "filterType":"TEXT",
                                        "format":"EEE dd-MM-yyyy",
                                        "headerTitle":"Date",
                                        "minWidth":110,
                                        "svyUUID":"65F6877A-8392-512F-96A5-1907FDB3CC23"
                                    },
                                    {
                                        "dataprovider":"shift_id",
                                        "filterType":"VALUELIST",
                                        "headerTitle":"Shift",
                                        "minWidth":110,
                                        "svyUUID":"AE393B79-315C-57B6-B7AE-4577B98A6B41",
                                        "valuelist":"EB21EBB8-FA70-546E-8D0D-6621F7B072B5"
                                    },
                                    {
                                        "dataprovider":"check_in",
                                        "filterType":"TEXT",
                                        "format":"HH:mm",
                                        "headerTitle":"In",
                                        "minWidth":110,
                                        "svyUUID":"86AD41CC-231E-54A0-A617-B0E304E57022"
                                    },
                                    {
                                        "dataprovider":"check_out",
                                        "filterType":"TEXT",
                                        "format":"HH:mm",
                                        "headerTitle":"Out",
                                        "minWidth":110,
                                        "svyUUID":"6030B950-BE71-534C-95BD-7E3ACF0D00B8"
                                    },
                                    {
                                        "dataprovider":"worked_minutes",
                                        "filterType":"TEXT",
                                        "headerTitle":"Worked (min)",
                                        "minWidth":110,
                                        "svyUUID":"E241C6C9-920D-55F0-BF9D-E09AFF114212"
                                    },
                                    {
                                        "dataprovider":"late_minutes",
                                        "filterType":"TEXT",
                                        "headerTitle":"Late (min)",
                                        "minWidth":110,
                                        "svyUUID":"A8B2957D-E41D-56D1-9C0E-93EC162FDD3B"
                                    },
                                    {
                                        "dataprovider":"overtime_minutes",
                                        "filterType":"TEXT",
                                        "headerTitle":"OT (min)",
                                        "minWidth":110,
                                        "svyUUID":"3CAEE520-C61D-5F92-B2A3-19FA734BE552"
                                    },
                                    {
                                        "dataprovider":"status",
                                        "filterType":"VALUELIST",
                                        "headerTitle":"Status",
                                        "minWidth":110,
                                        "showAs":"html",
                                        "svyUUID":"D6F0A974-A8CE-5CE1-912A-29E0FE766D30",
                                        "valuelist":"03506EDE-09FA-5173-A770-2F8744724922"
                                    },
                                    {
                                        "dataprovider":"remarks",
                                        "filterType":"TEXT",
                                        "headerTitle":"Remarks",
                                        "minWidth":110,
                                        "svyUUID":"CB8AB5BB-AF8B-54C4-A92C-F900CED54383"
                                    }
                                ],
                                "location":{
                                    "x":3,
                                    "y":3
                                },
                                "myFoundset":{
                                    "foundsetSelector":""
                                },
                                "readOnly":true,
                                "responsiveHeight":440,
                                "rowHeight":32
                            },
                            "location":"3,3",
                            "name":"grid",
                            "typeName":"aggrid-groupingtable",
                            "typeid":47,
                            "uuid":"6683B237-7A6F-572F-983B-BE01191F373F"
                        }
                    ],
                    "location":"3,3",
                    "typeid":46,
                    "uuid":"5A223DC2-5ECE-558E-98EB-2F16FA6D078F"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"C44D810B-C239-52BD-97FA-12EFD2ACFC84"
        }
    ],
    "name":"my_attendance",
    "navigatorID":"-1",
    "onLoadMethodID":"F9FF8143-6A79-54B8-A595-82B76A395008",
    "onShowMethodID":"FEF63A0F-A008-54C5-851E-C5B998239F0C",
    "typeid":3,
    "uuid":"32C8C994-EEBE-5954-9211-B78D7EC58601"
}