{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/raw_punches",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-hand-pointer",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Manual Punches"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"AD5A6190-37D0-5573-A727-5A871CF63AA8"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"C072439F-97BA-5A9C-8C6B-E2DB4C1EDD67"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"CB78DA57-91AB-5229-81F0-D0D36C0FA21C"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"card-panel"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"div"
                        }
                    },
                    "items":[
                        {
                            "json":{
                                "location":{
                                    "x":1,
                                    "y":1
                                },
                                "styleClass":"card-title",
                                "text":"Select employee and day"
                            },
                            "location":"1,1",
                            "typeName":"bootstrapcomponents-label",
                            "typeid":47,
                            "uuid":"27A42919-A2D6-5506-B347-270C7578A623"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-5 mb-3"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"form-label",
                                                "text":"Employee"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"24BBDCA5-1487-54FA-ADD7-65245D244247"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"selEmployee",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onDataChangeMethodID":"DC996C8F-7A4E-58B9-8694-495D48AE0162",
                                                "placeholderText":"Select employee",
                                                "valuelistID":"1878CB17-9579-5E12-9933-F3B964B5551E"
                                            },
                                            "location":"2,2",
                                            "name":"fld_employee",
                                            "typeName":"bootstrapcomponents-combobox",
                                            "typeid":47,
                                            "uuid":"042AB7A5-6267-5A7D-B3D7-B0296322EB97"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"A5F1C3FA-4BB8-59C9-843A-804669EFEC89"
                                },
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-3 mb-3"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"form-label",
                                                "text":"Day"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"265A6842-CFAD-5948-AFD4-821AE7EBF104"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"selDate",
                                                "format":"EEE dd-MM-yyyy",
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "onDataChangeMethodID":"DC996C8F-7A4E-58B9-8694-495D48AE0162",
                                                "styleClass":"form-control"
                                            },
                                            "location":"2,2",
                                            "name":"fld_day",
                                            "typeName":"bootstrapcomponents-calendar",
                                            "typeid":47,
                                            "uuid":"E2DED6F8-3950-57ED-ABFD-91F1212ACFD4"
                                        }
                                    ],
                                    "location":"2,2",
                                    "typeid":46,
                                    "uuid":"F2BCF472-FCDC-5759-A3C8-CD054102BA4A"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"8180D518-61B4-5F92-922C-5DB2972AA83D"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"A89786B0-E259-5291-A25C-BB3321875AF8"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-6"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Punches"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"5C92E963-70D3-5375-8916-8EC34BC34920"
                                        },
                                        {
                                            "json":{
                                                "columns":[
                                                    {
                                                        "dataprovider":"punch_time",
                                                        "format":"dd-MM-yyyy HH:mm",
                                                        "headerTitle":"Time",
                                                        "minWidth":110,
                                                        "svyUUID":"DF389BF4-835B-593B-B3CD-018FB162AE6F"
                                                    },
                                                    {
                                                        "dataprovider":"punch_type",
                                                        "headerTitle":"In / Out",
                                                        "minWidth":110,
                                                        "svyUUID":"F2A6EDF7-8409-568A-B003-668D614EF0D4",
                                                        "valuelist":"63C47D86-C7FD-5BB2-A769-B831C8217E1D"
                                                    },
                                                    {
                                                        "dataprovider":"remarks",
                                                        "headerTitle":"Remarks",
                                                        "minWidth":110,
                                                        "svyUUID":"5DE3FC17-2F4D-5982-8F79-6C0CE2A0B417"
                                                    },
                                                    {
                                                        "dataprovider":"source",
                                                        "headerTitle":"Source",
                                                        "minWidth":110,
                                                        "svyUUID":"A6D22539-0CA9-5618-80C7-73F14196B15E"
                                                    }
                                                ],
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "myFoundset":{
                                                    "foundsetSelector":""
                                                },
                                                "readOnly":true,
                                                "responsiveHeight":260,
                                                "rowHeight":32
                                            },
                                            "location":"2,2",
                                            "name":"grid",
                                            "typeName":"aggrid-groupingtable",
                                            "typeid":47,
                                            "uuid":"2B79977A-F43F-5020-8984-FAB382F06C2C"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"0742A905-2C5C-5D35-BB51-038B10914F3E"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"80EA77AE-F413-59CF-B41F-85E9F03C9B38"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-6"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Add or edit punch"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"35DEE465-3242-51C4-A8CF-71BDD1A7CDC3"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-7 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_time",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Date and time"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"2008332F-7E97-5B75-9EE3-13F39CEF95D6"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"punch_time",
                                                                "format":"dd-MM-yyyy HH:mm",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_time",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"76CA4F59-8082-537A-A4A5-C7A110A83448"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"5947F661-EFA8-5DEA-82D7-233F17B87250"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-5 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_type",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"In / Out"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"54D708B5-A65B-5AE6-A9D0-66AAAA72BD64"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"punch_type",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "valuelistID":"63C47D86-C7FD-5BB2-A769-B831C8217E1D"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_type",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"DAFD5CA2-4141-5CAD-B60D-CBBA92D24967"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"80A93E02-CB71-5E3E-B423-6DD7C9C52F6F"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"3E571CC4-9DBB-525E-B019-046E58486E2A"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_remarks",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Remarks"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"FAB8A39D-AC28-5407-A00B-B3DB05F64544"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"remarks",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"e.g. forgot to punch, approved by manager",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_remarks",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"EFB60AB1-EB53-59EE-97FE-C061D02F8273"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"C6B50C2E-93CE-583A-8215-E679D3A5E6F3"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"6DCEA647-B061-5F6B-87AA-F70DFA44AFC0"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3 crud-buttons"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-plus",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "onActionMethodID":"C2A41BF0-6271-5DA1-8CB3-E68AB43F4EC8",
                                                                "styleClass":"btn btn-outline-primary me-2",
                                                                "text":"New"
                                                            },
                                                            "location":"1,1",
                                                            "name":"btn_new",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"8A64EF9C-AC01-5A75-8AC8-6405E1ED78BF"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-save",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"0FA7C3B1-DE19-5012-A6E5-6E6AEB01E65A",
                                                                "styleClass":"btn btn-primary me-2",
                                                                "text":"Save"
                                                            },
                                                            "location":"2,2",
                                                            "name":"btn_save",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"1DD8CF9E-5A86-548F-97DD-30E2C055FB76"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-undo",
                                                                "location":{
                                                                    "x":3,
                                                                    "y":3
                                                                },
                                                                "onActionMethodID":"D3590E6E-65F3-5413-8432-659FF968EDD0",
                                                                "styleClass":"btn btn-outline-secondary me-2",
                                                                "text":"Cancel"
                                                            },
                                                            "location":"3,3",
                                                            "name":"btn_cancel",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"DFB73FF8-D2D2-5933-8F49-EA333180C5A6"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-trash",
                                                                "location":{
                                                                    "x":4,
                                                                    "y":4
                                                                },
                                                                "onActionMethodID":"55E69C7D-A193-5E62-A9BD-2B14741F4BD8",
                                                                "styleClass":"btn btn-outline-danger",
                                                                "text":"Delete"
                                                            },
                                                            "location":"4,4",
                                                            "name":"btn_delete",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"78656798-9710-5C2A-955D-44795B1B5126"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"80BF01B4-71A5-583B-83EE-67A4B0C49E81"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"C0211FF1-DC22-5A62-AF0D-02ED07530460"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"183DE079-56C1-5F43-A0D8-D37197D6FB8A"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"A3E356B8-7990-559B-A37E-346069FCBB76"
                        }
                    ],
                    "location":"3,3",
                    "typeid":46,
                    "uuid":"AB4D01E0-0CF3-5FAA-BDDE-8E08C0F2030C"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "dataProviderID":"resultText",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"alert alert-info d-block"
                                    },
                                    "location":"1,1",
                                    "name":"lbl_result",
                                    "typeName":"bootstrapcomponents-datalabel",
                                    "typeid":47,
                                    "uuid":"884A3D2D-2903-55DE-A957-5E9995A0DFAE"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"41D94E67-0DB5-5113-81B5-8F8BB7E31E9E"
                        }
                    ],
                    "location":"4,4",
                    "typeid":46,
                    "uuid":"115C0EB4-4EF3-5397-B8A1-3F9CF5BFE514"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"FE7EC701-0849-5001-BBC6-BF3D4980BDE9"
        }
    ],
    "name":"punches",
    "navigatorID":"-1",
    "onLoadMethodID":"FAA0A63A-49D3-5C38-B778-1902440922C2",
    "onShowMethodID":"2AECBB97-971C-5702-AAD4-4C8BEF9C7BD3",
    "typeid":3,
    "uuid":"17734913-7A1C-5F0F-81D6-F9D35BB2B4F9"
}