{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-palette",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Settings"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"41EBB6B4-FF93-512D-B50B-C469616F432A"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"E07D3BD3-3422-526D-AE1F-657AA95E2BD7"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"017FF676-99EF-50EE-AB88-E5D3D9F342DF"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-6"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Organisation"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"D3321C6B-136E-5443-8EE1-47E42FBB0780"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_app_name",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Application name (sidebar)"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"909D1964-3739-530A-BAB8-71E97E5E50CB"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"scopes.settings.appName",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onDataChangeMethodID":"BEE63BEA-4A64-584B-AF02-916802174E4E",
                                                                "placeholderText":"HR Portal",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_app_name",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"7C34C75A-52AE-58CC-AC73-9A64AECCC851"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"AE940D4C-E9E7-57CC-9EDE-351E7408063C"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"3C078A02-BF0D-5DC7-8C18-F7739F77011A"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_company",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Company name (top bar)"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"75C073DE-43F9-5F93-B7B3-9AA262B82CE1"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"scopes.settings.companyName",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onDataChangeMethodID":"BEE63BEA-4A64-584B-AF02-916802174E4E",
                                                                "placeholderText":"My Company",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_company",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"5E8A2FF9-E22B-55B5-A76F-795BD0854761"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"BA64208D-3107-54DD-9080-D9F32177897D"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"F4E68BE0-EA55-565C-8A9A-89ACE2735D12"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"600042FF-B981-5824-B2D8-E5F7E3476F94"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"4E8E75D1-524D-5CB7-A6BB-011C3F20B9F6"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-6"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Theme"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"0DD70946-EA57-52AF-A4F9-79DBEE0DCEE8"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-2"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Preset colours"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"A5F48394-8F34-5F50-A3AA-9FCFB39930C5"
                                                        },
                                                        {
                                                            "customProperties":{
                                                                "attributes":{
                                                                    "class":"swatches"
                                                                },
                                                                "properties":{
                                                                    "packagename":"12grid",
                                                                    "specname":"div"
                                                                }
                                                            },
                                                            "items":[
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":1,
                                                                            "y":1
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-blue",
                                                                        "text":"",
                                                                        "toolTipText":"Blue"
                                                                    },
                                                                    "location":"1,1",
                                                                    "name":"preset_blue",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"0947F029-F572-5541-AB0F-1A808C53EBF2"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":2,
                                                                            "y":2
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-indigo",
                                                                        "text":"",
                                                                        "toolTipText":"Indigo"
                                                                    },
                                                                    "location":"2,2",
                                                                    "name":"preset_indigo",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"4BD40708-58EA-5627-B1EC-CF38D5974581"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":3,
                                                                            "y":3
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-teal",
                                                                        "text":"",
                                                                        "toolTipText":"Teal"
                                                                    },
                                                                    "location":"3,3",
                                                                    "name":"preset_teal",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"55D1EAAD-0694-5FB5-AE0F-4863C1B0B6AC"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":4,
                                                                            "y":4
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-cyan",
                                                                        "text":"",
                                                                        "toolTipText":"Cyan"
                                                                    },
                                                                    "location":"4,4",
                                                                    "name":"preset_cyan",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"E17638DC-C716-510D-BDD5-6A1A8DCE6D04"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":5,
                                                                            "y":5
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-green",
                                                                        "text":"",
                                                                        "toolTipText":"Green"
                                                                    },
                                                                    "location":"5,5",
                                                                    "name":"preset_green",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"C70DA2B1-408B-54CA-A458-60F774A846FC"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":6,
                                                                            "y":6
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-purple",
                                                                        "text":"",
                                                                        "toolTipText":"Purple"
                                                                    },
                                                                    "location":"6,6",
                                                                    "name":"preset_purple",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"DFC04212-3623-5065-A0C3-1E145C3E0A43"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":7,
                                                                            "y":7
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-pink",
                                                                        "text":"",
                                                                        "toolTipText":"Pink"
                                                                    },
                                                                    "location":"7,7",
                                                                    "name":"preset_pink",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"2439109C-EDBB-53A5-BBDF-D59FDDFE9C7E"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":8,
                                                                            "y":8
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-orange",
                                                                        "text":"",
                                                                        "toolTipText":"Orange"
                                                                    },
                                                                    "location":"8,8",
                                                                    "name":"preset_orange",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"AF7CD6C5-01FC-5D18-AC93-949946932BAD"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":9,
                                                                            "y":9
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-red",
                                                                        "text":"",
                                                                        "toolTipText":"Red"
                                                                    },
                                                                    "location":"9,9",
                                                                    "name":"preset_red",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"C28C2769-89FE-556B-B220-FE761EB787E2"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":10,
                                                                            "y":10
                                                                        },
                                                                        "onActionMethodID":"FE8B9A28-839D-5F66-B45D-EC14F447CF5D",
                                                                        "styleClass":"btn swatch swatch-slate",
                                                                        "text":"",
                                                                        "toolTipText":"Slate"
                                                                    },
                                                                    "location":"10,10",
                                                                    "name":"preset_slate",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"BABA970E-79A2-5AD1-8E2E-E954466D0070"
                                                                }
                                                            ],
                                                            "location":"2,2",
                                                            "typeid":46,
                                                            "uuid":"22EA3E46-3057-5982-8D94-3B6F330C8ED6"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"81380ED1-97DB-58CF-9386-6758C22A7CF3"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"CF502B9F-F940-5A49-BCF1-15C022A4B475"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_color",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Colour"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"85D82C8D-03B6-5DFB-8D6A-E03CE13A81B9"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"scopes.settings.themeColor",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onDataChangeMethodID":"BEE63BEA-4A64-584B-AF02-916802174E4E",
                                                                "valuelistID":"A036B2B6-EE82-5B46-BE0D-84B6CDF2B919"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_color",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"17D2078E-AB92-5FB7-868A-B05B5C5EB04A"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"6A7C7EA3-ABB3-5F6E-855E-72EF4BBD3241"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_sidebar",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Sidebar style"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"A55E58F9-C615-5DCB-B35B-9C342DFD25CB"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"scopes.settings.sidebarStyle",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onDataChangeMethodID":"BEE63BEA-4A64-584B-AF02-916802174E4E",
                                                                "valuelistID":"914B51F3-B8D5-53ED-9771-56D98A8B7CB4"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_sidebar",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"E5C4FC92-2EC7-5071-A0E0-8AA477DD6C68"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"5E4969F8-D239-558C-8F37-FF4C41C7535D"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"6411E5A4-C0DB-5AB3-8556-69DC3EB60239"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-2"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Preview"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"3E1D9F6C-DFE0-5FD9-AA87-B34B5E9FE2F6"
                                                        },
                                                        {
                                                            "customProperties":{
                                                                "attributes":{
                                                                    "class":"theme-preview"
                                                                },
                                                                "properties":{
                                                                    "packagename":"12grid",
                                                                    "specname":"div"
                                                                }
                                                            },
                                                            "items":[
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":1,
                                                                            "y":1
                                                                        },
                                                                        "onActionMethodID":"507E2E21-A6DC-5B17-BFB1-E37A9D6469A0",
                                                                        "styleClass":"btn btn-primary me-2",
                                                                        "text":"Primary"
                                                                    },
                                                                    "location":"1,1",
                                                                    "name":"prev_primary",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"834B98FB-16C2-59BD-9A21-8F26EFC3CD91"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":2,
                                                                            "y":2
                                                                        },
                                                                        "onActionMethodID":"507E2E21-A6DC-5B17-BFB1-E37A9D6469A0",
                                                                        "styleClass":"btn btn-outline-primary me-2",
                                                                        "text":"Outline"
                                                                    },
                                                                    "location":"2,2",
                                                                    "name":"prev_outline",
                                                                    "typeName":"bootstrapcomponents-button",
                                                                    "typeid":47,
                                                                    "uuid":"E9A10D81-66E7-51B6-ABA3-22C6C5D406A7"
                                                                },
                                                                {
                                                                    "json":{
                                                                        "location":{
                                                                            "x":3,
                                                                            "y":3
                                                                        },
                                                                        "styleClass":"badge bg-primary",
                                                                        "text":"Badge"
                                                                    },
                                                                    "location":"3,3",
                                                                    "typeName":"bootstrapcomponents-label",
                                                                    "typeid":47,
                                                                    "uuid":"4D8EFE37-3239-5D17-9A94-0E6783A94BD5"
                                                                }
                                                            ],
                                                            "location":"2,2",
                                                            "typeid":46,
                                                            "uuid":"71A4AC44-6089-5678-A6E0-4BC23A946C9E"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"32D98BCD-BA73-56B8-9823-E639EB481F04"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"D699494E-797C-5D89-827E-2B25CB7A7075"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"293A356F-5DB5-5822-A834-0269C817FF12"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"CDCA4279-72B3-5B56-970B-67EB84A04DF8"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"FB2AA252-99DF-56FB-928E-9D04621E3006"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mb-4"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-save",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "onActionMethodID":"A68531B3-7C05-5D85-B77D-F761BBEC26B2",
                                        "styleClass":"btn btn-primary me-2",
                                        "text":"Save"
                                    },
                                    "location":"1,1",
                                    "name":"btn_save",
                                    "typeName":"bootstrapcomponents-button",
                                    "typeid":47,
                                    "uuid":"FC114752-6116-5829-9B97-0354BF0D11B1"
                                },
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-undo",
                                        "location":{
                                            "x":2,
                                            "y":2
                                        },
                                        "onActionMethodID":"91FF41F2-B66D-5BC8-9923-DDCCFB96DCF0",
                                        "styleClass":"btn btn-outline-secondary",
                                        "text":"Cancel"
                                    },
                                    "location":"2,2",
                                    "name":"btn_cancel",
                                    "typeName":"bootstrapcomponents-button",
                                    "typeid":47,
                                    "uuid":"079F27CE-76C1-538F-B00A-32598D7B5280"
                                },
                                {
                                    "json":{
                                        "location":{
                                            "x":3,
                                            "y":3
                                        },
                                        "styleClass":"help-text ms-3",
                                        "text":"Colour changes preview immediately; press Save to keep them."
                                    },
                                    "location":"3,3",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"CF33A769-71BB-5E81-A9B5-410C6A788A79"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"488F99AA-3EBD-5A77-9C42-C7E50C1DFC7F"
                        }
                    ],
                    "location":"3,3",
                    "typeid":46,
                    "uuid":"6AB8F61A-21E0-5F75-AD2B-497BF3B9A942"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"7084ED1E-07F1-5B75-82A2-DC23CFA66B96"
        }
    ],
    "name":"settings",
    "navigatorID":"-1",
    "onHideMethodID":"AA7218C8-3871-59B1-9D41-DC2790387738",
    "onShowMethodID":"15B94588-19EA-5D95-8790-5CAF33823D04",
    "typeid":3,
    "uuid":"EEB46E39-82C2-5DA8-97ED-7A399DBDC795"
}