{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid login-page"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row justify-content-center"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-sm-10 col-md-7 col-lg-5"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel login-card"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"login-brand",
                                                "text":"Welcome - first-time setup"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"5ADF2E4A-40C9-5B6A-ACE9-2FEFE12A63F4"
                                        },
                                        {
                                            "json":{
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "styleClass":"help-text d-block mb-3",
                                                "text":"Create the administrator account. You can add other users afterwards under System > Users."
                                            },
                                            "location":"2,2",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"CA1C0BFF-953C-56E7-A255-7DA00BE50F6D"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_username",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Administrator username"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"13D9026A-18C6-53EB-8105-7264DE6EDEE0"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"username",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"admin",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_username",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"81F1CD58-B6FF-55F2-B0C7-3A413B74161B"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"45CDE124-ED92-5655-AC67-A86EC4FD7581"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"4BFA9AF7-E77A-582B-ABDC-CCF069B2A62D"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_password",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Password"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"C764EC6C-C996-5400-AC3C-3884CD531E6B"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"password",
                                                                "inputType":"password",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"At least 8 characters, letters and numbers",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_password",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"354FFE86-D80A-5519-9C0B-BFB8123426BB"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"094C46A6-635B-53A6-ACB0-1C1E8DAABE69"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_confirm",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Confirm password"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"C2AEB8EF-DA7A-5AEA-A6E5-E19538B91C58"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"confirm",
                                                                "inputType":"password",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"D8AF0AC0-9BDC-53A4-A945-AD0C87C80988",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_confirm",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"6B44F856-A663-5C99-A240-0143C05C66D9"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"E7F6EF3C-F088-5CC4-A5EF-6CE33CCCFB8A"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"8C97BACB-6D07-5E86-9AC2-D3B70292C048"
                                        },
                                        {
                                            "json":{
                                                "dataProviderID":"setupError",
                                                "location":{
                                                    "x":5,
                                                    "y":5
                                                },
                                                "showAs":"text",
                                                "styleClass":"login-error"
                                            },
                                            "location":"5,5",
                                            "name":"lbl_error",
                                            "typeName":"bootstrapcomponents-datalabel",
                                            "typeid":47,
                                            "uuid":"A5580904-69DF-5AE8-947A-9F94742714B4"
                                        },
                                        {
                                            "json":{
                                                "imageStyleClass":"fa fa-user-shield",
                                                "location":{
                                                    "x":6,
                                                    "y":6
                                                },
                                                "onActionMethodID":"D8AF0AC0-9BDC-53A4-A945-AD0C87C80988",
                                                "styleClass":"btn btn-primary w-100",
                                                "text":"Create administrator"
                                            },
                                            "location":"6,6",
                                            "name":"btn_create",
                                            "typeName":"bootstrapcomponents-button",
                                            "typeid":47,
                                            "uuid":"15A72990-65B2-5DBF-B67A-C2A3609C4AA7"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"67D5D201-49EC-557F-89B9-14BF0B23D688"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"45C905D8-2DF8-53AE-9DDA-699005E7CE65"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"3A9374EF-BC45-5FF7-8CA1-7DA8AFAF3B6C"
                },
                {
                    "json":{
                        "dataProviderID":"scopes.settings.appName",
                        "location":{
                            "x":2,
                            "y":2
                        },
                        "styleClass":"d-none",
                        "styleClassExpression":"scopes.settings.themeClass"
                    },
                    "location":"2,2",
                    "name":"theme_marker",
                    "typeName":"bootstrapcomponents-datalabel",
                    "typeid":47,
                    "uuid":"D495F846-C9C7-5A41-B2B4-CF4997BB81C6"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"20784265-AE91-5B12-BA91-408D723F7336"
        }
    ],
    "name":"setup",
    "navigatorID":"-1",
    "onShowMethodID":"E5473A65-3FB7-56A2-B0E0-94E2F37C8846",
    "typeid":3,
    "uuid":"F4BCBBD2-592B-5F34-B64C-395AE6827E48"
}