{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/shifts",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-clock",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Shifts"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"33B2CE8D-B7A4-52C8-8F55-E459081CEEC3"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"C6A8D5A0-6901-5651-B20C-C8E7660F59C9"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"6F4DD905-8517-5707-A5A9-9D8723AFFEF4"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-6"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"grid-toolbar"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"div"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "json":{
                                                        "location":{
                                                            "x":1,
                                                            "y":1
                                                        },
                                                        "styleClass":"card-title",
                                                        "text":"Shifts"
                                                    },
                                                    "location":"1,1",
                                                    "typeName":"bootstrapcomponents-label",
                                                    "typeid":47,
                                                    "uuid":"8B721E2B-26D2-5ED9-8E1C-26E2E2A3758F"
                                                },
                                                {
                                                    "json":{
                                                        "imageStyleClass":"fa fa-file-excel",
                                                        "location":{
                                                            "x":2,
                                                            "y":2
                                                        },
                                                        "onActionMethodID":"0BBCDB6A-DDB6-5726-9846-1AD13EF0BDAE",
                                                        "styleClass":"btn btn-sm btn-outline-secondary",
                                                        "text":"Export",
                                                        "toolTipText":"Download as CSV (opens in Excel)"
                                                    },
                                                    "location":"2,2",
                                                    "name":"btn_export",
                                                    "typeName":"bootstrapcomponents-button",
                                                    "typeid":47,
                                                    "uuid":"0219E995-1A8E-5544-9543-F410764DC8B2"
                                                }
                                            ],
                                            "location":"1,1",
                                            "typeid":46,
                                            "uuid":"077C3D1C-3A4C-5A26-8891-A425A9D115D1"
                                        },
                                        {
                                            "json":{
                                                "columns":[
                                                    {
                                                        "dataprovider":"code",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Code",
                                                        "minWidth":110,
                                                        "svyUUID":"CA2A792A-46DB-5660-B490-5DFF66E5AE07"
                                                    },
                                                    {
                                                        "dataprovider":"name",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Name",
                                                        "minWidth":110,
                                                        "svyUUID":"CB3AA123-8D2E-5C37-A10D-8A4C2B77934D"
                                                    },
                                                    {
                                                        "dataprovider":"start_time",
                                                        "filterType":"TEXT",
                                                        "format":"HH:mm",
                                                        "headerTitle":"Start",
                                                        "minWidth":110,
                                                        "svyUUID":"D93F739A-1121-5B63-A8B3-AB470C5122AC"
                                                    },
                                                    {
                                                        "dataprovider":"end_time",
                                                        "filterType":"TEXT",
                                                        "format":"HH:mm",
                                                        "headerTitle":"End",
                                                        "minWidth":110,
                                                        "svyUUID":"70B1FC3C-2CB6-52DF-9DFF-E2E2120DE54A"
                                                    },
                                                    {
                                                        "dataprovider":"crosses_midnight",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Overnight",
                                                        "minWidth":110,
                                                        "svyUUID":"E9496E2D-9D3A-51CC-A404-980063E2C42A",
                                                        "valuelist":"097FA9DA-DE6C-5D6D-855D-115609AA2E1B"
                                                    }
                                                ],
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "myFoundset":{
                                                    "foundsetSelector":""
                                                },
                                                "readOnly":true,
                                                "responsiveHeight":450,
                                                "rowHeight":32
                                            },
                                            "location":"2,2",
                                            "name":"grid",
                                            "typeName":"aggrid-groupingtable",
                                            "typeid":47,
                                            "uuid":"06E8CDC7-E802-53F4-A52B-1E210A6945D2"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"098CBB23-C721-52F3-B4F4-690E31DBB204"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"984BB781-D54E-58BD-9277-4A70023E1B68"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-6"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Details"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"2229BF34-090A-5DD4-B8DA-6DA0E9D14E64"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-5 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_code",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Code"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"26D1D3E5-9F81-59A5-A1F3-0AEEC5AD791C"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"code",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"e.g. MORNING",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_code",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"0E3913D2-CF59-552D-9D2A-A773100AF300"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"669BF32C-99E7-53E4-BC34-11E7D349FEC0"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-7 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_name",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Name"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"2980A788-548F-5173-9735-713A15818C1C"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"name",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Shift name",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_name",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"A87B183B-D64E-54BD-BEDB-85B3651FEDF3"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"CF33AFC0-5DC1-59CC-BDD8-BF51429DEA00"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"02BA8EC3-EA46-5B68-935E-B34CE29FC291"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_start",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Start time"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"3EAC8E66-A764-59BD-A6EB-0E7E5ADF9EED"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"start_time",
                                                                "format":"HH:mm",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onDataChangeMethodID":"B2244878-EBBF-5A5A-9694-947B03823D14",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_start",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"56181810-DEBA-5320-B24C-4A82D3D44CA6"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"28B9E32B-0C93-590A-8822-D319C9642DAF"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_end",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"End time"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"DF175FD4-31A7-51BD-A4D6-60DD2BC0216C"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"end_time",
                                                                "format":"HH:mm",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onDataChangeMethodID":"B2244878-EBBF-5A5A-9694-947B03823D14",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_end",
                                                            "typeName":"bootstrapcomponents-calendar",
                                                            "typeid":47,
                                                            "uuid":"40755CDF-79B7-5934-A156-FA62FE571EC4"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"7304906E-BFEC-5C24-85BD-6FCE323452A2"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_overnight",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Overnight"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"35C201C0-DD14-5626-8FC4-37B0B227B02C"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"crosses_midnight",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Ends next day"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_overnight",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"C3141022-8C60-5B7F-B077-E53118D97295"
                                                        }
                                                    ],
                                                    "location":"3,3",
                                                    "typeid":46,
                                                    "uuid":"1D239F65-2AA4-508D-BB3C-6DF03069B63C"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"FB2D6E01-7EA3-5420-B5AF-E745B7731677"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_grace",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Grace (min)"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"E435F851-7B2F-574C-A194-18F352BC7D68"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"grace_minutes",
                                                                "format":"#",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_grace",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"705BCE72-41C5-5750-B8EB-4EFBF68FDDDE"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"AFD4BF2E-7352-5F4A-8302-08F02F8B8EA7"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_break",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Break (min)"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"CC7A206B-2690-5D62-8BC8-7683F2701CB0"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"break_minutes",
                                                                "format":"#",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_break",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"6F3FB210-593B-5FB4-9B13-E3072DBB649C"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"E05B17D6-8B47-5B03-802A-5F6595ABC404"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_early",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Early check-in window (min)"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"D218DBE0-7797-5C34-98FD-72C656825F5E"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"early_in_window_minutes",
                                                                "format":"#",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_early",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"9C5E5508-CAAC-52BB-A0D2-00BAD219F31E"
                                                        }
                                                    ],
                                                    "location":"3,3",
                                                    "typeid":46,
                                                    "uuid":"50A5E862-84AC-5DEA-8656-914E6EEC3993"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"923C7ABB-3E0C-558B-B9D5-3EA3D621374E"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_full",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Full day = worked min"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"6B5B271F-8835-5680-91AA-0C7CBF6B4F50"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"full_day_minutes",
                                                                "format":"#",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_full",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"D278139A-CA54-5B36-9F86-B757D0EC4EFE"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"BF413D8F-7E29-534E-9C4E-7810A1C5EE7B"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_half",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Half day = worked min"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"83E2DC2D-9650-5A11-9F72-0950578B83E8"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"half_day_minutes",
                                                                "format":"#",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_half",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"D5686E53-345D-5EFA-B71B-31B8A41D2E9C"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"BC4B160F-0505-5D57-8B00-F198AD6D7B8B"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-4 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_color",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Colour"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"0E4B3E07-84C2-5429-BCA0-24C688B6416C"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"color",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"#4CAF50",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_color",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"F8FBD971-2063-5DA8-8499-05A575CAF4EF"
                                                        }
                                                    ],
                                                    "location":"3,3",
                                                    "typeid":46,
                                                    "uuid":"DACD9821-F0C0-5DE9-8FB3-BEEE8A23B293"
                                                }
                                            ],
                                            "location":"5,5",
                                            "typeid":46,
                                            "uuid":"3179DCF2-2A48-5CB4-890F-8068EDBEDFD6"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_active",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Status"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"027EE574-4D03-569D-9ED3-8EFA90D53FFB"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"is_active",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Active"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_active",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"26A69206-1B97-5DF2-A5E6-A1A69EA084F9"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"FC78ADBA-9E4F-54A6-83C8-371E1912FE05"
                                                }
                                            ],
                                            "location":"6,6",
                                            "typeid":46,
                                            "uuid":"2CED7866-0976-5091-A478-B272965A6773"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3 crud-buttons"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-plus",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "onActionMethodID":"7FB74ACD-CE76-5C9A-92EB-216016AF55F2",
                                                                "styleClass":"btn btn-outline-primary me-2",
                                                                "text":"New"
                                                            },
                                                            "location":"1,1",
                                                            "name":"btn_new",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"A4FC323B-BF76-5158-B02F-1EA0D93FC390"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-save",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"DB8DBF8C-F87F-589A-9976-A8E38021B26B",
                                                                "styleClass":"btn btn-primary me-2",
                                                                "text":"Save"
                                                            },
                                                            "location":"2,2",
                                                            "name":"btn_save",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"E749842D-2BC3-59E3-BB45-487A2C223099"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-undo",
                                                                "location":{
                                                                    "x":3,
                                                                    "y":3
                                                                },
                                                                "onActionMethodID":"8D4BFCC7-4625-5AAD-B73A-D2783AF3FAA7",
                                                                "styleClass":"btn btn-outline-secondary me-2",
                                                                "text":"Cancel"
                                                            },
                                                            "location":"3,3",
                                                            "name":"btn_cancel",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"E4FB3761-47F6-5361-8D4E-0B1CB6522251"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-trash",
                                                                "location":{
                                                                    "x":4,
                                                                    "y":4
                                                                },
                                                                "onActionMethodID":"23148482-CFA9-5C1B-8B9D-9A1D6285F187",
                                                                "styleClass":"btn btn-outline-danger",
                                                                "text":"Delete"
                                                            },
                                                            "location":"4,4",
                                                            "name":"btn_delete",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"B877C236-6FE5-5431-904B-B562AD7997FA"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"3E6DB891-E210-5062-AE4F-2D34727D7264"
                                                }
                                            ],
                                            "location":"7,7",
                                            "typeid":46,
                                            "uuid":"46BBCAF6-32ED-591C-B310-308CA12530E5"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"F3785E51-33D4-5F80-B381-185216E99831"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"F27A0A7A-FE31-5B41-8A37-44E907FA90E0"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"EBDACC03-6978-5016-9F2E-64E5A4783A76"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"73F32CBC-B5F9-5786-82BF-B9D20EABC9E7"
        }
    ],
    "name":"shifts",
    "navigatorID":"-1",
    "onLoadMethodID":"EFD33A17-6B77-5AC6-AE3D-0C73EA848E0B",
    "onShowMethodID":"A0261054-6058-54F7-8952-493E9249B7EF",
    "typeid":3,
    "uuid":"9980EB6F-7DC8-5CD0-8D9F-B424FEA5D5FE"
}