{
    "customProperties":{
        "layout":{
            "responsive":true
        }
    },
    "dataSource":"db:/attendance/app_users",
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"container-fluid"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"container"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-12 mt-3 mb-3"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "json":{
                                        "imageStyleClass":"fa fa-user-shield",
                                        "location":{
                                            "x":1,
                                            "y":1
                                        },
                                        "styleClass":"h3 page-title",
                                        "text":"Users"
                                    },
                                    "location":"1,1",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"8C0E3F0E-B27E-56E2-AAA5-000F681225DA"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"6196AA7E-1EEA-5493-B4BE-F3AC93373AC0"
                        }
                    ],
                    "location":"1,1",
                    "typeid":46,
                    "uuid":"626CE63B-FBA8-53FB-9B35-242019609194"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"row"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"row"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-7"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"grid-toolbar"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"div"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "json":{
                                                        "location":{
                                                            "x":1,
                                                            "y":1
                                                        },
                                                        "styleClass":"card-title",
                                                        "text":"Users"
                                                    },
                                                    "location":"1,1",
                                                    "typeName":"bootstrapcomponents-label",
                                                    "typeid":47,
                                                    "uuid":"6491ACD7-3E26-521D-95E4-4A7950ADBDF4"
                                                },
                                                {
                                                    "json":{
                                                        "imageStyleClass":"fa fa-file-excel",
                                                        "location":{
                                                            "x":2,
                                                            "y":2
                                                        },
                                                        "onActionMethodID":"ACCF7F53-B9E6-540F-8188-4A2FAD20CF78",
                                                        "styleClass":"btn btn-sm btn-outline-secondary",
                                                        "text":"Export",
                                                        "toolTipText":"Download as CSV (opens in Excel)"
                                                    },
                                                    "location":"2,2",
                                                    "name":"btn_export",
                                                    "typeName":"bootstrapcomponents-button",
                                                    "typeid":47,
                                                    "uuid":"BC682153-46F1-52BB-87D1-4CEF52F8F05F"
                                                }
                                            ],
                                            "location":"1,1",
                                            "typeid":46,
                                            "uuid":"C3701C1C-406C-538D-8046-8D843904B207"
                                        },
                                        {
                                            "json":{
                                                "columns":[
                                                    {
                                                        "dataprovider":"username",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Username",
                                                        "minWidth":110,
                                                        "svyUUID":"7AD303A3-D2B6-5E58-92C3-3A304A1B68CD"
                                                    },
                                                    {
                                                        "dataprovider":"role",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Role",
                                                        "minWidth":110,
                                                        "svyUUID":"46A89108-3452-542F-895F-BE10AC1C3958",
                                                        "valuelist":"6803F38C-2E32-5B56-9C23-FA57938AD805"
                                                    },
                                                    {
                                                        "dataprovider":"employee_id",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Employee",
                                                        "minWidth":110,
                                                        "svyUUID":"1F70FBE0-E4D1-55B0-BF83-1DB9E635D80F",
                                                        "valuelist":"1878CB17-9579-5E12-9933-F3B964B5551E"
                                                    },
                                                    {
                                                        "dataprovider":"is_active",
                                                        "filterType":"VALUELIST",
                                                        "headerTitle":"Active",
                                                        "minWidth":110,
                                                        "svyUUID":"A8116AF4-5031-5FFB-82E2-D9F2738B474C",
                                                        "valuelist":"097FA9DA-DE6C-5D6D-855D-115609AA2E1B"
                                                    },
                                                    {
                                                        "dataprovider":"last_login",
                                                        "filterType":"TEXT",
                                                        "format":"dd-MM-yyyy HH:mm",
                                                        "headerTitle":"Last login",
                                                        "minWidth":110,
                                                        "svyUUID":"941AD3E7-41B4-542C-9BD7-CDACCBB9BBEA"
                                                    },
                                                    {
                                                        "dataprovider":"failed_login_count",
                                                        "filterType":"TEXT",
                                                        "headerTitle":"Failed logins",
                                                        "minWidth":110,
                                                        "svyUUID":"51B7E1CD-2F8A-5867-AF17-EB0FF132390D"
                                                    }
                                                ],
                                                "location":{
                                                    "x":2,
                                                    "y":2
                                                },
                                                "myFoundset":{
                                                    "foundsetSelector":""
                                                },
                                                "readOnly":true,
                                                "responsiveHeight":450,
                                                "rowHeight":32
                                            },
                                            "location":"2,2",
                                            "name":"grid",
                                            "typeName":"aggrid-groupingtable",
                                            "typeid":47,
                                            "uuid":"2FE03190-E79E-5263-A629-72DF3B6B1394"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"D4ED7420-E12F-5658-83E0-317D3565C8A1"
                                }
                            ],
                            "location":"1,1",
                            "typeid":46,
                            "uuid":"51F36D97-48B4-50A6-A652-35CC74FBAEFE"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"col-lg-5"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"column"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"card-panel"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"card-title",
                                                "text":"Details"
                                            },
                                            "location":"1,1",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"716280D7-2C84-59DB-8007-62EEF604EB4A"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_username",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Username"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"28873F85-E54A-5568-A1FF-57A7C7A51D91"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"username",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"e.g. ali.khan",
                                                                "styleClass":"form-control"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_username",
                                                            "typeName":"bootstrapcomponents-textbox",
                                                            "typeid":47,
                                                            "uuid":"3CF2475B-4441-5DC1-8FEE-ACA03942C0B9"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"9BC576AB-DAA0-5083-BDF2-96F5E0106423"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_role",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Role"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"86FD7EB5-C3EF-5937-B35B-FE2D75612F07"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"role",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "valuelistID":"6803F38C-2E32-5B56-9C23-FA57938AD805"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_role",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"F09FA49F-ED05-5463-BF7D-017B7408F7CF"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"CC73789C-F380-5088-8068-B0D85BEFF002"
                                                }
                                            ],
                                            "location":"2,2",
                                            "typeid":46,
                                            "uuid":"9183B519-44FF-5BEA-9544-1CF256E94EF2"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"fld_employee",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Linked employee"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"9F6DF078-71DF-5BBB-9A84-D6EE3EBD81A3"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"employee_id",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "placeholderText":"Select employee",
                                                                "valuelistID":"1878CB17-9579-5E12-9933-F3B964B5551E"
                                                            },
                                                            "location":"2,2",
                                                            "name":"fld_employee",
                                                            "typeName":"bootstrapcomponents-combobox",
                                                            "typeid":47,
                                                            "uuid":"26C2D350-6D93-5FF3-AFC5-2106BD6EDED9"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"768EC4AF-9602-5B84-A053-D3B5CF319035"
                                                }
                                            ],
                                            "location":"3,3",
                                            "typeid":46,
                                            "uuid":"CB1B6B58-9B9D-5D2F-BABF-AF9273D51103"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_active",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Status"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"3A34B44B-4C42-5DB6-BFC4-5609828E4CF4"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"is_active",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Active"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_active",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"12690BF4-580E-5349-AA6B-E05FC22CC66C"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"3923D178-47EA-568D-870B-7877E5122E4F"
                                                },
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-6 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"chk_must_change",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"\u00a0"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"D92E2036-1993-5F4A-B767-7030A914F1CB"
                                                        },
                                                        {
                                                            "json":{
                                                                "dataProviderID":"must_change_password",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "text":"Must change password at next sign-in"
                                                            },
                                                            "location":"2,2",
                                                            "name":"chk_must_change",
                                                            "typeName":"bootstrapcomponents-checkbox",
                                                            "typeid":47,
                                                            "uuid":"5EC81472-6A16-5DBB-9D19-A0E893F80D2D"
                                                        }
                                                    ],
                                                    "location":"2,2",
                                                    "typeid":46,
                                                    "uuid":"B72FACB2-24B9-5B5D-800B-BCC438DC4C09"
                                                }
                                            ],
                                            "location":"4,4",
                                            "typeid":46,
                                            "uuid":"2D76BEC5-8D34-5D1A-9B88-4695B6488F0D"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12 mb-3"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "labelFor":"btn_reset",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "styleClass":"form-label",
                                                                "text":"Password"
                                                            },
                                                            "location":"1,1",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"4363D670-C84B-543C-AE75-1EC77CE2D5A1"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-key",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"022A984D-ACBE-5DB0-BAB9-70465C99A625",
                                                                "styleClass":"btn btn-outline-warning",
                                                                "text":"Reset password"
                                                            },
                                                            "location":"2,2",
                                                            "name":"btn_reset",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"E9B8F890-2D2A-5DCB-9B58-BD8D6A39CF32"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"19CA1A86-7C59-5931-8BAE-67DDB190C29B"
                                                }
                                            ],
                                            "location":"5,5",
                                            "typeid":46,
                                            "uuid":"EF69DCAA-16B1-5364-8598-24CF587F2946"
                                        },
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-12 mb-3 crud-buttons"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-plus",
                                                                "location":{
                                                                    "x":1,
                                                                    "y":1
                                                                },
                                                                "onActionMethodID":"267F5D1E-9984-525D-A34D-9849AEE3D040",
                                                                "styleClass":"btn btn-outline-primary me-2",
                                                                "text":"New"
                                                            },
                                                            "location":"1,1",
                                                            "name":"btn_new",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"647EEC36-9099-502B-9C79-7A6C93192D31"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-save",
                                                                "location":{
                                                                    "x":2,
                                                                    "y":2
                                                                },
                                                                "onActionMethodID":"E2117D0C-02CE-5E3D-87F8-B8DAE8289384",
                                                                "styleClass":"btn btn-primary me-2",
                                                                "text":"Save"
                                                            },
                                                            "location":"2,2",
                                                            "name":"btn_save",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"3E0C58C4-6A84-57F9-B968-E761BAD92087"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-undo",
                                                                "location":{
                                                                    "x":3,
                                                                    "y":3
                                                                },
                                                                "onActionMethodID":"9C49F3E4-8FC4-50BE-9999-41D78A88ECAC",
                                                                "styleClass":"btn btn-outline-secondary me-2",
                                                                "text":"Cancel"
                                                            },
                                                            "location":"3,3",
                                                            "name":"btn_cancel",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"C4D962FB-7525-596C-AFBB-6244097E6E2D"
                                                        },
                                                        {
                                                            "json":{
                                                                "imageStyleClass":"fa fa-trash",
                                                                "location":{
                                                                    "x":4,
                                                                    "y":4
                                                                },
                                                                "onActionMethodID":"1AFBE348-3797-56C0-83E2-0622B3BB965D",
                                                                "styleClass":"btn btn-outline-danger",
                                                                "text":"Delete"
                                                            },
                                                            "location":"4,4",
                                                            "name":"btn_delete",
                                                            "typeName":"bootstrapcomponents-button",
                                                            "typeid":47,
                                                            "uuid":"CD9A04C5-E032-5D76-92CD-C6D7707580F0"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"FF9D0332-EEF6-53D3-AFCD-C5D0E30519E2"
                                                }
                                            ],
                                            "location":"6,6",
                                            "typeid":46,
                                            "uuid":"DB8F192E-AF54-5F6F-AF43-3EB2808F2A4D"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"0FA70592-34E3-59C6-8CC8-10E3072E0BBC"
                                }
                            ],
                            "location":"2,2",
                            "typeid":46,
                            "uuid":"DB6617FA-0300-5207-B896-E4AB127740E1"
                        }
                    ],
                    "location":"2,2",
                    "typeid":46,
                    "uuid":"DC5D8FD4-E9EA-56B2-A3FA-39905EE9E98D"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"EB639A61-0757-5560-AA02-CD38060A0E3A"
        }
    ],
    "name":"users",
    "navigatorID":"-1",
    "onLoadMethodID":"5162C60B-F416-56F8-94B5-06894FD4FF69",
    "onShowMethodID":"832499C2-2898-5DC3-AC69-B68327F058A4",
    "typeid":3,
    "uuid":"D5892F76-0117-5F6F-9DD6-E35AA2FEF031"
}